/**
 * Order Validation Constants
 *
 * Business rules and validation constraints for Order entity:
 * - Field length limits
 * - Numeric ranges
 * - Required field rules
 * - Format patterns
 *
 * Based on Dataverse schema in Table_Order.csv
 */

/**
 * Field length constraints
 */
export const ORDER_FIELD_LENGTH = {
  /**
   * Order Number (Autonumber)
   * Format: osot_ord-0000001
   * Generated by Dataverse, not user-provided
   */
  ORDER_NUMBER_PREFIX: 'osot_ord',
  ORDER_NUMBER_SEED: 1,
  ORDER_NUMBER_DIGITS: 7,

  /**
   * Coupon code max length
   * Dataverse: Single line of text (100 characters)
   */
  COUPON_MAX: 100,

  /**
   * Coupon code min length
   * Business rule: Minimum 1 character for meaningful code
   */
  COUPON_MIN: 1,
} as const;

/**
 * Numeric field constraints
 */
export const ORDER_NUMERIC_CONSTRAINTS = {
  /**
   * Subtotal constraints (Currency field)
   * Dataverse Currency: 0 to 922,337,203,685,477
   * Business rule: Must be >= 0
   */
  SUBTOTAL_MIN: 0,
  SUBTOTAL_MAX: 922337203685477,

  /**
   * Total constraints (Currency field)
   * Dataverse Currency: 0 to 922,337,203,685,477
   * Business rule: Must be >= 0
   */
  TOTAL_MIN: 0,
  TOTAL_MAX: 922337203685477,

  /**
   * Coupon discount constraint
   * Maximum possible discount value
   */
  COUPON_DISCOUNT_MIN: 0,
  COUPON_DISCOUNT_MAX: 999999.99,
} as const;

/**
 * Order-level validation rules
 */
export const ORDER_VALIDATION_RULES = {
  /**
   * At least one of account or affiliate must be present
   * - If person buying: account required, affiliate optional
   * - If organization buying: affiliate required, account optional
   */
  REQUIRES_ACCOUNT_OR_AFFILIATE: true,

  /**
   * Organization is always required (multi-tenant)
   */
  REQUIRES_ORGANIZATION: true,

  /**
   * Subtotal is required
   */
  REQUIRES_SUBTOTAL: true,

  /**
   * Total is required
   */
  REQUIRES_TOTAL: true,

  /**
   * At least one OrderProduct must exist
   * Cannot create empty orders
   */
  REQUIRES_ORDER_PRODUCTS: true,

  /**
   * Total calculation validation
   * Total must equal: subtotal - coupon_discount + sum(line_item_taxes)
   * Or more specifically: sum(line_items) - coupon_discount = total
   */
  VALIDATE_TOTAL_CALCULATION: true,
} as const;

/**
 * Coupon validation rules
 */
export const COUPON_VALIDATION_RULES = {
  /**
   * Coupon code pattern
   * Alphanumeric with underscores/hyphens allowed
   * Example: "DISCOUNT15", "SUMMER_2025", "OSOT-MEMBER-5"
   */
  PATTERN: /^[A-Z0-9_-]+$/i,

  /**
   * Coupon code is optional
   */
  OPTIONAL: true,

  /**
   * If coupon provided, it must be valid
   * Validation against Coupon entity will happen in business rules service
   */
} as const;

/**
 * Financial calculation rules
 */
export const FINANCIAL_CALCULATION_RULES = {
  /**
   * Currency precision (decimal places)
   * All currency fields use 2 decimal places
   */
  CURRENCY_DECIMALS: 2,

  /**
   * Rounding strategy for calculations
   * Use standard banker's rounding (round half to even)
   */
  ROUNDING_STRATEGY: 'BANKER',

  /**
   * Maximum allowed rounding difference
   * Calculated total vs actual total must not exceed this
   */
  ROUNDING_TOLERANCE: 0.01,
} as const;

/**
 * Business relationship validation
 */
export const BUSINESS_RELATIONSHIP_VALIDATION = {
  /**
   * Account and organization must be related
   * If both are provided, account.organization must equal order.organization
   */
  VALIDATE_ACCOUNT_ORGANIZATION_MATCH: true,

  /**
   * Affiliate and organization must be related
   * If both are provided, affiliate.organization must equal order.organization
   */
  VALIDATE_AFFILIATE_ORGANIZATION_MATCH: true,

  /**
   * Cannot have both account and affiliate as "primary"
   * Business rule: Either person (account) or company (affiliate), not both
   */
  VALIDATE_MUTUAL_EXCLUSIVITY: false, // Soft rule - both can exist but one is primary

  /**
   * Only active/enabled accounts/affiliates can purchase
   * Check account.osot_active_member and affiliate.osot_status = 'Active'
   */
  VALIDATE_BUYER_STATUS: true,
} as const;

/**
 * Error messages for validation failures
 */
export const ORDER_VALIDATION_ERRORS = {
  REQUIRES_ACCOUNT_OR_AFFILIATE:
    'Order must have either an Account or Affiliate as buyer',
  REQUIRES_ORGANIZATION: 'Organization is required for order',
  REQUIRES_SUBTOTAL: 'Order subtotal is required',
  REQUIRES_TOTAL: 'Order total is required',
  REQUIRES_ORDER_PRODUCTS: 'Order must have at least one product',
  INVALID_TOTAL_CALCULATION:
    'Order total does not match calculated value (subtotal - coupon + taxes)',
  COUPON_CODE_INVALID: 'Coupon code format is invalid',
  COUPON_NOT_FOUND: 'Coupon code not found or expired',
  COUPON_NOT_APPLICABLE: 'Coupon is not applicable to this order',
  ACCOUNT_ORGANIZATION_MISMATCH:
    'Account does not belong to the specified organization',
  AFFILIATE_ORGANIZATION_MISMATCH:
    'Affiliate does not belong to the specified organization',
  INACTIVE_BUYER: 'Cannot create order - buyer is inactive or not eligible',
  INVALID_SUBTOTAL: 'Subtotal must be greater than or equal to 0',
  INVALID_TOTAL: 'Total must be greater than or equal to 0',
  TOTAL_LESS_THAN_SUBTOTAL:
    'Total cannot be less than subtotal (negative discount)',
} as const;
