import { AccessModifier } from '../../../../common/enums/access-modifier.enum';
import { Privilege } from '../../../../common/enums/privilege.enum';
import {
  getAccessModifierDisplayName,
  getPrivilegeDisplayName,
} from '../../../../common/enums';
import { formatPhoneNumber } from '../../../../utils/phone-formatter.utils';
import {
  sanitizeUrl,
  isUrlFromPlatform,
  SocialMediaPlatform,
} from '../../../../utils/url-sanitizer.utils';
import { CreateContactDto } from '../dtos/create-contact.dto';
import { CreateContactForAccountDto } from '../dtos/create-contact-for-account.dto';
import { UpdateContactDto } from '../dtos/update-contact.dto';
import { ContactResponseDto } from '../dtos/contact-response.dto';
import { ContactPublicDto } from '../dtos/contact-public.dto';

// Export the ContactResponseDto and ContactPublicDto types for external use
export { ContactResponseDto } from '../dtos/contact-response.dto';
export { ContactPublicDto } from '../dtos/contact-public.dto';

/**
 * Contact Mapper Module
 *
 * Advanced mapping layer with comprehensive data transformation and validation.
 *
 * Integration Features:
 * - AccessModifier and Privilege enum integration for type-safe permission mapping
 * - phone-formatter.utils integration for consistent Canadian phone number formatting
 * - url-sanitizer.utils integration for secure URL validation and normalization
 * - Platform-specific social media URL validation using SocialMediaPlatform enum
 * - Business website normalization with security-first approach (HTTPS enforcement)
 *
 * Project Utils Integration:
 * - formatPhoneNumber(): Ensures consistent (XXX) XXX-XXXX Canadian format
 * - sanitizeUrl(): Validates and normalizes URLs with security controls
 * - isUrlFromPlatform(): Validates social media URLs against platform domains
 * - SocialMediaPlatform enum: Type-safe platform identification
 *
 * Architecture Benefits:
 * - Centralized data transformation logic
 * - Consistent validation patterns across all Contact operations
 * - Security-first URL handling with automatic HTTPS enforcement
 * - Type-safe enum conversions preventing invalid data persistence
 * - Separation of internal vs public data interfaces
 */

/**
 * Contact Internal Interface
 *
 * Internal representation containing all fields from Table Contact.csv
 * Includes sensitive data - never expose directly to public APIs
 * Matches the existing DTO structure for consistency
 */
export interface ContactInternal {
  // Core identification (from CSV)
  osot_contact_id?: string; // Autonumber: osot-ct-0000001
  osot_table_contactid?: string; // GUID - unique identifier
  osot_table_account?: string; // Lookup to Account table

  // Business identifier (auto-generated by Dataverse - not included in create/update requests)
  osot_user_business_id: string; // Business required, max 20 chars (read-only)

  // Communication fields (from CSV)
  osot_secondary_email?: string; // Email format, max 255 chars
  osot_home_phone?: string; // Phone format, max 14 chars
  osot_work_phone?: string; // Phone format, max 14 chars

  // Professional information (from CSV)
  osot_job_title?: string; // Text format, max 50 chars
  osot_business_website?: string; // URL format, max 255 chars

  // Social media fields (from CSV) - matches DTO naming
  osot_facebook?: string; // URL format, max 255 chars
  osot_instagram?: string; // URL format, max 255 chars
  osot_tiktok?: string; // URL format, max 255 chars (matches DTO)
  osot_linkedin?: string; // URL format, max 255 chars

  // Security and access fields (from CSV) - matches DTO naming
  osot_access_modifiers?: AccessModifier; // Choice: Private/Public/etc
  osot_privilege?: Privilege; // Choice: Owner/Editor/Viewer/etc

  // System fields (from CSV)
  createdon?: string;
  modifiedon?: string;
  ownerid?: string;
}

/**
 * Helper functions for enum conversions and data parsing
 */

/**
 * Convert string/number to AccessModifier enum
 */
function parseAccessModifier(value: unknown): AccessModifier | undefined {
  if (typeof value === 'number') {
    return Object.values(AccessModifier).includes(value) ? value : undefined;
  }
  if (typeof value === 'string') {
    const numValue = parseInt(value, 10);
    if (!isNaN(numValue) && Object.values(AccessModifier).includes(numValue)) {
      return numValue;
    }
  }
  return undefined;
}

/**
 * Convert string/number to Privilege enum
 */
function parsePrivilege(value: unknown): Privilege | undefined {
  if (typeof value === 'number') {
    return Object.values(Privilege).includes(value) ? value : undefined;
  }
  if (typeof value === 'string') {
    const numValue = parseInt(value, 10);
    if (!isNaN(numValue) && Object.values(Privilege).includes(numValue)) {
      return numValue;
    }
  }
  return undefined;
}

/**
 * Normalize and validate email address
 * Uses consistent email validation patterns following project standards
 */
function normalizeEmail(email: string): string | undefined {
  if (!email || typeof email !== 'string') return undefined;

  const trimmed = email.trim().toLowerCase();
  const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

  return emailRegex.test(trimmed) ? trimmed : undefined;
}

/**
 * Normalize phone number using project phone-formatter.utils
 * Leverages formatPhoneNumber for consistent Canadian format
 */
function normalizePhoneNumber(phone: string): string | undefined {
  if (!phone || typeof phone !== 'string') return undefined;

  try {
    // Use project's phone formatter for consistent formatting
    const formatted = formatPhoneNumber(phone);
    return formatted.length <= 14 ? formatted : formatted.slice(0, 14);
  } catch {
    // If formatting fails, return original if valid length
    return phone.length <= 14 ? phone : phone.slice(0, 14);
  }
}

/**
 * Normalize and validate social media URL using project url-sanitizer.utils
 * Leverages sanitizeUrl and isUrlFromPlatform for platform-specific validation
 */
function normalizeSocialMediaUrl(
  url: string,
  platform: 'facebook' | 'instagram' | 'tiktok' | 'linkedin',
): string | undefined {
  if (!url || typeof url !== 'string') return undefined;

  try {
    // Map platform string to SocialMediaPlatform enum
    const platformMap: Record<string, SocialMediaPlatform> = {
      facebook: SocialMediaPlatform.FACEBOOK,
      instagram: SocialMediaPlatform.INSTAGRAM,
      tiktok: SocialMediaPlatform.TIKTOK,
      linkedin: SocialMediaPlatform.LINKEDIN,
    };

    const platformEnum = platformMap[platform];

    // Use project's URL sanitizer for consistent normalization
    const sanitized = sanitizeUrl(url, platformEnum, {
      allowHttp: false,
      maxLength: 255,
    });

    // Validate platform-specific URL using project utils
    if (!isUrlFromPlatform(sanitized, platformEnum)) {
      return undefined; // Invalid URL for platform
    }

    return sanitized;
  } catch {
    return undefined; // Invalid URL
  }
}

/**
 * Normalize business website URL using project url-sanitizer.utils
 * Leverages sanitizeUrl for consistent URL handling
 */
function normalizeBusinessWebsite(url: string): string | undefined {
  if (!url || typeof url !== 'string') return undefined;

  try {
    // Use project's URL sanitizer for consistent normalization
    return sanitizeUrl(url, SocialMediaPlatform.WEBSITE, {
      allowHttp: false,
      maxLength: 255,
    });
  } catch {
    return undefined; // Invalid URL
  }
}

/**
 * Map Dataverse raw data to internal interface (includes sensitive fields)
 * WARNING: Only use this internally - never expose ContactInternal to public APIs
 * Uses LOGICAL NAMES from Table Contact.csv as per Dataverse API standards
 */
export function mapDataverseToContactInternal(raw: unknown): ContactInternal {
  const out: ContactInternal = {} as ContactInternal;
  if (!raw || typeof raw !== 'object') return out;
  const r = raw as Record<string, unknown>;

  // Core identification fields (using Logical names from CSV)
  out.osot_contact_id = r.osot_contact_id as string; // Logical name: osot_contact_id
  out.osot_table_contactid = r.osot_table_contactid as string; // Logical name: osot_table_contactid
  out.osot_table_account = (r.osot_table_account ||
    r._osot_table_account_value) as string; // Logical name: osot_table_account

  // Business identifier (required field from CSV - logical name)
  out.osot_user_business_id = (r.osot_user_business_id as string) || ''; // Logical name: osot_user_business_id

  // Communication fields (using Logical names from CSV)
  out.osot_secondary_email = r.osot_secondary_email as string; // Logical name: osot_secondary_email
  out.osot_home_phone = r.osot_home_phone as string; // Logical name: osot_home_phone
  out.osot_work_phone = r.osot_work_phone as string; // Logical name: osot_work_phone

  // Professional information (using Logical names from CSV)
  out.osot_job_title = r.osot_job_title as string; // Logical name: osot_job_title
  out.osot_business_website = r.osot_business_website as string; // Logical name: osot_business_website

  // Social media fields (using Logical names from CSV)
  out.osot_facebook = r.osot_facebook as string; // Logical name: osot_facebook
  out.osot_instagram = r.osot_instagram as string; // Logical name: osot_instagram
  out.osot_tiktok = r.osot_tiktok as string; // Logical name: osot_tiktok
  out.osot_linkedin = r.osot_linkedin as string; // Logical name: osot_linkedin

  // Security fields with enum parsing (using Logical names from CSV)
  out.osot_access_modifiers = parseAccessModifier(r.osot_access_modifiers); // Logical name: osot_access_modifiers
  out.osot_privilege = parsePrivilege(r.osot_privilege); // Logical name: osot_privilege

  // System fields (using Logical names from CSV)
  out.createdon = r.createdon as string; // Logical name: createdon
  out.modifiedon = r.modifiedon as string; // Logical name: modifiedon
  out.ownerid = r.ownerid as string; // Logical name: ownerid

  return out;
}

/**
 * Map Dataverse response to public ContactResponseDto
 * Filters out sensitive internal fields and provides clean public interface
 */
export function mapDataverseToContactResponse(
  raw: unknown,
): ContactResponseDto | null {
  if (!raw || typeof raw !== 'object') return null;

  const internal = mapDataverseToContactInternal(raw);

  const response: ContactResponseDto = {
    osot_Contact_ID: internal.osot_contact_id,
    osot_table_contactid: internal.osot_table_contactid,
    osot_table_account: internal.osot_table_account,
    osot_user_business_id: internal.osot_user_business_id,
    osot_secondary_email: internal.osot_secondary_email,
    osot_home_phone: internal.osot_home_phone,
    osot_work_phone: internal.osot_work_phone,
    osot_job_title: internal.osot_job_title,
    osot_business_website: internal.osot_business_website,
    osot_facebook: internal.osot_facebook,
    osot_instagram: internal.osot_instagram,
    osot_tiktok: internal.osot_tiktok,
    osot_linkedin: internal.osot_linkedin,
    osot_access_modifiers: internal.osot_access_modifiers
      ? getAccessModifierDisplayName(internal.osot_access_modifiers)
      : undefined,
    osot_privilege: internal.osot_privilege
      ? getPrivilegeDisplayName(internal.osot_privilege)
      : undefined,
    createdon: internal.createdon,
    modifiedon: internal.modifiedon,
    ownerid: internal.ownerid,
  };

  return response;
}

/**
 * Map array of Dataverse responses to ContactResponseDto array
 * Handles bulk operations and list responses
 */
export function mapDataverseArrayToContactResponse(
  rawArray: unknown[],
): ContactResponseDto[] {
  if (!Array.isArray(rawArray)) return [];

  return rawArray
    .map(mapDataverseToContactResponse)
    .filter((contact): contact is ContactResponseDto => contact !== null);
}

/**
 * Map ContactInternal to ContactPublicDto
 * Used when returning filtered contact data for public API endpoints
 * Excludes system fields (GUIDs, timestamps, relationships, access control)
 */
export function mapInternalToPublicDto(
  internal: ContactInternal,
): ContactPublicDto {
  return {
    osot_secondary_email: internal.osot_secondary_email,
    osot_home_phone: internal.osot_home_phone,
    osot_work_phone: internal.osot_work_phone,
    osot_job_title: internal.osot_job_title,
    osot_business_website: internal.osot_business_website,
    osot_facebook: internal.osot_facebook,
    osot_instagram: internal.osot_instagram,
    osot_tiktok: internal.osot_tiktok,
    osot_linkedin: internal.osot_linkedin,
  };
}

/**
 * Map ContactResponseDto to ContactPublicDto
 * Used in controllers to filter response DTOs before returning to public API
 * Removes sensitive/internal fields (GUIDs, timestamps, relationships, access control)
 */
export function mapResponseDtoToPublicDto(
  response: ContactResponseDto,
): ContactPublicDto {
  return {
    osot_secondary_email: response.osot_secondary_email,
    osot_home_phone: response.osot_home_phone,
    osot_work_phone: response.osot_work_phone,
    osot_job_title: response.osot_job_title,
    osot_business_website: response.osot_business_website,
    osot_facebook: response.osot_facebook,
    osot_instagram: response.osot_instagram,
    osot_tiktok: response.osot_tiktok,
    osot_linkedin: response.osot_linkedin,
  };
}

/**
 * Map CreateContactDto to ContactInternal format
 * Standard transformation for create operations following Account/Affiliate pattern
 */
export function mapCreateDtoToInternal(
  dto: CreateContactDto,
): Partial<ContactInternal> {
  const internal: Partial<ContactInternal> = {
    // Communication fields (raw - normalization happens in repository/business rules)
    osot_secondary_email: dto.osot_secondary_email,
    osot_home_phone: dto.osot_home_phone,
    osot_work_phone: dto.osot_work_phone,

    // Professional information
    osot_job_title: dto.osot_job_title,
    osot_business_website: dto.osot_business_website,

    // Social media profiles
    osot_facebook: dto.osot_facebook,
    osot_instagram: dto.osot_instagram,
    osot_tiktok: dto.osot_tiktok,
    osot_linkedin: dto.osot_linkedin,
  };

  // Relationship fields (OData binding - preserved from DTO)
  if (dto['osot_Table_Account@odata.bind']) {
    internal['osot_Table_Account@odata.bind'] =
      dto['osot_Table_Account@odata.bind'];
    internal.osot_table_account = extractAccountIdFromBinding(
      dto['osot_Table_Account@odata.bind'],
    );
  }

  return internal;
}

/**
 * Map CreateContactDto to Dataverse payload format
 * Applies normalization and validation rules
 */
export function mapCreateDtoToDataverse(
  dto: CreateContactDto,
): Record<string, unknown> {
  const payload: Record<string, unknown> = {};

  // Note: osot_user_business_id is auto-generated by Dataverse, not included in create requests

  // Account relationship (using correct Logical name for binding)
  if (dto['osot_Table_Account@odata.bind']) {
    payload['osot_table_account@odata.bind'] =
      dto['osot_Table_Account@odata.bind'];
  }

  // Note: System fields like osot_table_contactid, osot_contact_id are auto-generated by Dataverse

  // Communication fields with normalization
  if (dto.osot_secondary_email) {
    const normalizedEmail = normalizeEmail(dto.osot_secondary_email);
    if (normalizedEmail) {
      payload.osot_secondary_email = normalizedEmail;
    }
  }

  if (dto.osot_home_phone) {
    const normalizedPhone = normalizePhoneNumber(dto.osot_home_phone);
    if (normalizedPhone) {
      payload.osot_home_phone = normalizedPhone;
    }
  }

  if (dto.osot_work_phone) {
    const normalizedPhone = normalizePhoneNumber(dto.osot_work_phone);
    if (normalizedPhone) {
      payload.osot_work_phone = normalizedPhone;
    }
  }

  // Professional information
  if (dto.osot_job_title) {
    payload.osot_job_title = dto.osot_job_title.trim().slice(0, 50);
  }

  if (dto.osot_business_website) {
    const normalizedWebsite = normalizeBusinessWebsite(
      dto.osot_business_website,
    );
    if (normalizedWebsite) {
      payload.osot_business_website = normalizedWebsite;
    }
  }

  // Social media with platform-specific validation
  if (dto.osot_facebook) {
    const normalizedFacebook = normalizeSocialMediaUrl(
      dto.osot_facebook,
      'facebook',
    );
    if (normalizedFacebook) {
      payload.osot_facebook = normalizedFacebook;
    }
  }

  if (dto.osot_instagram) {
    const normalizedInstagram = normalizeSocialMediaUrl(
      dto.osot_instagram,
      'instagram',
    );
    if (normalizedInstagram) {
      payload.osot_instagram = normalizedInstagram;
    }
  }

  if (dto.osot_tiktok) {
    const normalizedTikTok = normalizeSocialMediaUrl(dto.osot_tiktok, 'tiktok');
    if (normalizedTikTok) {
      payload.osot_tiktok = normalizedTikTok;
    }
  }

  if (dto.osot_linkedin) {
    const normalizedLinkedIn = normalizeSocialMediaUrl(
      dto.osot_linkedin,
      'linkedin',
    );
    if (normalizedLinkedIn) {
      payload.osot_linkedin = normalizedLinkedIn;
    }
  }

  // Security fields (osot_access_modifiers, osot_privilege) are handled by system
  // Set default values for system-controlled security fields
  payload.osot_access_modifiers = AccessModifier.PRIVATE; // Default: Private
  payload.osot_privilege = Privilege.OWNER; // Default: Owner

  return payload;
}

/**
 * Map UpdateContactDto to Dataverse payload format
 * Only includes fields that are being updated
 */
export function mapUpdateDtoToDataverse(
  dto: UpdateContactDto,
): Record<string, unknown> {
  const payload: Record<string, unknown> = {};

  // Note: osot_user_business_id is auto-generated by Dataverse, cannot be updated

  // Account relationship (if being updated - using correct Logical name for binding)
  if (dto['osot_Table_Account@odata.bind'] !== undefined) {
    payload['osot_table_account@odata.bind'] =
      dto['osot_Table_Account@odata.bind'];
  }

  // Communication fields with normalization
  if (dto.osot_secondary_email !== undefined) {
    if (dto.osot_secondary_email) {
      const normalizedEmail = normalizeEmail(dto.osot_secondary_email);
      payload.osot_secondary_email = normalizedEmail || null;
    } else {
      payload.osot_secondary_email = null; // Clear the field
    }
  }

  if (dto.osot_home_phone !== undefined) {
    if (dto.osot_home_phone) {
      const normalizedPhone = normalizePhoneNumber(dto.osot_home_phone);
      payload.osot_home_phone = normalizedPhone || null;
    } else {
      payload.osot_home_phone = null;
    }
  }

  if (dto.osot_work_phone !== undefined) {
    if (dto.osot_work_phone) {
      const normalizedPhone = normalizePhoneNumber(dto.osot_work_phone);
      payload.osot_work_phone = normalizedPhone || null;
    } else {
      payload.osot_work_phone = null;
    }
  }

  // Professional information
  if (dto.osot_job_title !== undefined) {
    payload.osot_job_title = dto.osot_job_title
      ? dto.osot_job_title.trim().slice(0, 50)
      : null;
  }

  if (dto.osot_business_website !== undefined) {
    if (dto.osot_business_website) {
      const normalizedWebsite = normalizeBusinessWebsite(
        dto.osot_business_website,
      );
      payload.osot_business_website = normalizedWebsite || null;
    } else {
      payload.osot_business_website = null;
    }
  }

  // Social media with platform-specific validation
  if (dto.osot_facebook !== undefined) {
    if (dto.osot_facebook) {
      const normalizedFacebook = normalizeSocialMediaUrl(
        dto.osot_facebook,
        'facebook',
      );
      payload.osot_facebook = normalizedFacebook || null;
    } else {
      payload.osot_facebook = null;
    }
  }

  if (dto.osot_instagram !== undefined) {
    if (dto.osot_instagram) {
      const normalizedInstagram = normalizeSocialMediaUrl(
        dto.osot_instagram,
        'instagram',
      );
      payload.osot_instagram = normalizedInstagram || null;
    } else {
      payload.osot_instagram = null;
    }
  }

  if (dto.osot_tiktok !== undefined) {
    if (dto.osot_tiktok) {
      const normalizedTikTok = normalizeSocialMediaUrl(
        dto.osot_tiktok,
        'tiktok',
      );
      payload.osot_tiktok = normalizedTikTok || null;
    } else {
      payload.osot_tiktok = null;
    }
  }

  if (dto.osot_linkedin !== undefined) {
    if (dto.osot_linkedin) {
      const normalizedLinkedIn = normalizeSocialMediaUrl(
        dto.osot_linkedin,
        'linkedin',
      );
      payload.osot_linkedin = normalizedLinkedIn || null;
    } else {
      payload.osot_linkedin = null;
    }
  }

  // Security fields (osot_access_modifiers, osot_privilege) are handled by system
  // and not included in user update requests

  return payload;
}

/**
 * Map CreateContactForAccountDto to ContactInternal
 * Used specifically for account integration workflow with repository pattern
 * Includes relationship fields (osot_user_business_id and @odata.bind)
 */
export function mapCreateContactForAccountDtoToInternal(
  dto: CreateContactForAccountDto,
): Partial<ContactInternal> {
  const internal: Partial<ContactInternal> = {
    // CRITICAL: Include relationship fields for account integration
    osot_user_business_id: dto.osot_user_business_id,

    // Communication fields
    osot_secondary_email: dto.osot_secondary_email,
    osot_job_title: dto.osot_job_title,
    osot_home_phone: dto.osot_home_phone,
    osot_work_phone: dto.osot_work_phone,
    osot_business_website: dto.osot_business_website,

    // Social media fields
    osot_facebook: dto.osot_facebook,
    osot_instagram: dto.osot_instagram,
    osot_tiktok: dto.osot_tiktok,
    osot_linkedin: dto.osot_linkedin,
  };

  // Handle OData binding for account relationship - keep as-is, don't extract GUID
  const odataBinding = dto['osot_Table_Account@odata.bind'];
  if (
    odataBinding &&
    typeof odataBinding === 'string' &&
    odataBinding.trim() !== ''
  ) {
    // Keep OData binding as-is for Dataverse navigation property
    Object.assign(internal, {
      'osot_Table_Account@odata.bind': odataBinding,
    });
  }

  return internal;
}

/**
 * Map CreateContactForAccountDto to Dataverse payload
 * Used specifically for account integration workflow
 * Includes relationship fields (osot_user_business_id and @odata.bind)
 */
export function mapCreateContactForAccountDtoToDataverse(
  dto: CreateContactForAccountDto,
): Record<string, unknown> {
  const payload: Record<string, unknown> = {};

  // CRITICAL: Include relationship fields for account integration
  if (dto.osot_user_business_id !== undefined) {
    payload.osot_user_business_id = dto.osot_user_business_id;
  }

  // Handle OData binding for account relationship - keep as-is, don't extract GUID
  const odataBinding = dto['osot_Table_Account@odata.bind'];
  if (
    odataBinding &&
    typeof odataBinding === 'string' &&
    odataBinding.trim() !== ''
  ) {
    payload['osot_table_account@odata.bind'] = odataBinding;
  }

  // Communication fields with normalization
  if (dto.osot_secondary_email) {
    const normalizedEmail = normalizeEmail(dto.osot_secondary_email);
    if (normalizedEmail) {
      payload.osot_secondary_email = normalizedEmail;
    }
  }

  if (dto.osot_home_phone) {
    const normalizedPhone = normalizePhoneNumber(dto.osot_home_phone);
    if (normalizedPhone) {
      payload.osot_home_phone = normalizedPhone;
    }
  }

  if (dto.osot_work_phone) {
    const normalizedPhone = normalizePhoneNumber(dto.osot_work_phone);
    if (normalizedPhone) {
      payload.osot_work_phone = normalizedPhone;
    }
  }

  if (dto.osot_job_title) {
    payload.osot_job_title = dto.osot_job_title;
  }

  // Website with validation and normalization
  if (dto.osot_business_website) {
    const sanitizedUrl = sanitizeUrl(dto.osot_business_website);
    if (sanitizedUrl) {
      payload.osot_business_website = sanitizedUrl;
    }
  }

  // Social media fields with platform-specific validation
  if (dto.osot_facebook) {
    const sanitizedUrl = sanitizeUrl(dto.osot_facebook);
    if (
      sanitizedUrl &&
      isUrlFromPlatform(sanitizedUrl, SocialMediaPlatform.FACEBOOK)
    ) {
      payload.osot_facebook = sanitizedUrl;
    }
  }

  if (dto.osot_instagram) {
    const sanitizedUrl = sanitizeUrl(dto.osot_instagram);
    if (
      sanitizedUrl &&
      isUrlFromPlatform(sanitizedUrl, SocialMediaPlatform.INSTAGRAM)
    ) {
      payload.osot_instagram = sanitizedUrl;
    }
  }

  if (dto.osot_tiktok) {
    const sanitizedUrl = sanitizeUrl(dto.osot_tiktok);
    if (
      sanitizedUrl &&
      isUrlFromPlatform(sanitizedUrl, SocialMediaPlatform.TIKTOK)
    ) {
      payload.osot_tiktok = sanitizedUrl;
    }
  }

  if (dto.osot_linkedin) {
    const sanitizedUrl = sanitizeUrl(dto.osot_linkedin);
    if (
      sanitizedUrl &&
      isUrlFromPlatform(sanitizedUrl, SocialMediaPlatform.LINKEDIN)
    ) {
      payload.osot_linkedin = sanitizedUrl;
    }
  }

  return payload;
}

/**
 * Extract account ID from OData binding string
 * Helper function for services that need to extract account ID
 */
export function extractAccountIdFromBinding(binding: string): string {
  if (!binding || typeof binding !== 'string') return '';

  const match = binding.match(/\(([^)]+)\)/);
  return match ? match[1] : '';
}

/**
 * Create social media summary from contact data
 * Useful for analytics and reporting
 */
export function createSocialMediaSummary(
  contact: ContactInternal | ContactResponseDto,
): {
  platforms: string[];
  urls: Record<string, string>;
  hasProfile: boolean;
  completenessScore: number; // 0-100
} {
  const platforms: string[] = [];
  const urls: Record<string, string> = {};

  const socialFields = [
    { key: 'facebook', value: contact.osot_facebook },
    { key: 'instagram', value: contact.osot_instagram },
    { key: 'tiktok', value: contact.osot_tiktok },
    { key: 'linkedin', value: contact.osot_linkedin },
  ];

  socialFields.forEach(({ key, value }) => {
    if (value && typeof value === 'string' && value.trim()) {
      platforms.push(key);
      urls[key] = value;
    }
  });

  const hasProfile = platforms.length > 0;
  const completenessScore = Math.round(
    (platforms.length / socialFields.length) * 100,
  );

  return {
    platforms,
    urls,
    hasProfile,
    completenessScore,
  };
}

/**
 * Create communication summary from contact data
 * Useful for contact management and outreach planning
 */
export function createCommunicationSummary(
  contact: ContactInternal | ContactResponseDto,
): {
  hasEmail: boolean;
  hasHomePhone: boolean;
  hasWorkPhone: boolean;
  hasWebsite: boolean;
  preferredMethod: 'email' | 'phone' | 'social' | 'website' | 'none';
  contactPoints: number;
} {
  const hasEmail = !!contact.osot_secondary_email?.trim();
  const hasHomePhone = !!contact.osot_home_phone?.trim();
  const hasWorkPhone = !!contact.osot_work_phone?.trim();
  const hasWebsite = !!contact.osot_business_website?.trim();

  const socialSummary = createSocialMediaSummary(contact);

  let preferredMethod: 'email' | 'phone' | 'social' | 'website' | 'none' =
    'none';

  if (hasEmail) {
    preferredMethod = 'email';
  } else if (hasWorkPhone) {
    preferredMethod = 'phone';
  } else if (socialSummary.hasProfile) {
    preferredMethod = 'social';
  } else if (hasWebsite) {
    preferredMethod = 'website';
  }

  const contactPoints = [
    hasEmail,
    hasHomePhone,
    hasWorkPhone,
    hasWebsite,
    socialSummary.hasProfile,
  ].filter(Boolean).length;

  return {
    hasEmail,
    hasHomePhone,
    hasWorkPhone,
    hasWebsite,
    preferredMethod,
    contactPoints,
  };
}
