/**
 * Basic Membership Preference DTO
 * Complete version with all fields including system-generated ones
 *
 * ESSENTIAL MODULES INTEGRATION:
 * - Base DTO used by Update operations
 * - Includes complete business rule validation for all fields
 * - Integrates with DataverseService for full entity management
 * - Contains both user-provided and system-generated fields
 *
 * DATAVERSE INTEGRATION:
 * - Preference ID format: osot-pref-0000001 (auto-generated)
 * - UUID primary key (osot_preference_id)
 * - System timestamps (createdon, modifiedon)
 * - Three lookup relationships with @odata.bind patterns
 * - Complete OData entity representation
 *
 * USAGE CONTEXT:
 * - Extended by Update DTO for PATCH operations
 * - Internal service layer processing
 * - Mapping between Dataverse and Internal representations
 * - Full entity state management
 *
 * BUSINESS RULES:
 * - All user-provided fields follow same validation as Create DTO
 * - System fields are read-only in normal operations
 * - Preference ID must follow osot-pref-NNNNNNN format
 * - Table must be "osot_table_membership_preferences"
 * - Timestamps managed by Dataverse
 */

import { ApiProperty } from '@nestjs/swagger';
import {
  IsString,
  IsNotEmpty,
  IsOptional,
  IsEnum,
  IsBoolean,
  IsDate,
  IsUUID,
  IsArray,
  Validate,
  Allow,
} from 'class-validator';
import { Type } from 'class-transformer';

// Essential modules integration
import { Privilege, AccessModifier } from '../../../../common/enums';

// Local enums integration
import { ThirdParties } from '../enums/third-parties.enum';
import { PracticePromotion } from '../enums/practice-promotion.enum';
import { SearchTools } from '../enums/search-tools.enum';
import { PsychotherapySupervision } from '../enums/psychotherapy-supervision.enum';

// Validators integration
import {
  MembershipYearPreferenceValidator,
  ExclusiveUserReferencePreferenceValidator,
  LookupRequiredValidator,
  ThirdPartiesValidator,
  PracticePromotionValidator,
  SearchToolsValidator,
  PsychotherapySupervisionValidator,
  ShadowingValidator,
  AutoRenewalValidator,
  PrivilegePreferenceValidator,
  AccessModifiersPreferenceValidator,
  PreferenceIdValidator,
} from '../validators/membership-preference.validators';

export class MembershipPreferenceBasicDto {
  // ========================================
  // SYSTEM PRIMARY KEY FIELD
  // ========================================

  @ApiProperty({
    example: 'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
    description:
      'Unique UUID primary key (auto-generated by Dataverse, optional for create)',
    type: 'string',
    format: 'uuid',
    required: false,
  })
  @IsOptional()
  @IsUUID('4', { message: 'Preference ID must be a valid UUID v4' })
  osot_preference_id?: string;

  // ========================================
  // SYSTEM IDENTIFIER FIELD
  // ========================================

  @ApiProperty({
    example: 'osot-pref-0000001',
    description:
      'Business identifier (auto-generated, format: osot-pref-NNNNNNN, optional for create)',
    type: 'string',
    required: false,
  })
  @IsOptional()
  @IsString({ message: 'Preference identifier must be a string' })
  @Validate(PreferenceIdValidator)
  osot_preference?: string;

  // ========================================
  // SYSTEM TABLE FIELD
  // ========================================

  @ApiProperty({
    example: 'osot_table_membership_preferences',
    description:
      'Table name (system field, always "osot_table_membership_preferences")',
    type: 'string',
    required: false,
  })
  @IsOptional()
  @IsString({ message: 'Table name must be a string' })
  osot_table?: string;

  // ========================================
  // BUSINESS REQUIRED FIELDS
  // ========================================

  @ApiProperty({
    example: '2025',
    description: 'Membership year (4-digit year, Business required)',
    type: 'string',
    minLength: 4,
    maxLength: 4,
  })
  @IsNotEmpty({ message: 'Membership year is required' })
  @IsString({ message: 'Membership year must be a string' })
  @Validate(MembershipYearPreferenceValidator)
  osot_membership_year: string;

  @ApiProperty({
    example: false,
    description:
      'Auto renewal preference (boolean, Business required, default: false)',
    type: 'boolean',
  })
  @IsNotEmpty({ message: 'Auto renewal is required' })
  @IsBoolean({ message: 'Auto renewal must be a boolean' })
  @Validate(AutoRenewalValidator)
  osot_auto_renewal: boolean;

  @ApiProperty({
    example: true,
    description:
      'Membership declaration - User acceptance of membership terms and conditions (boolean, Business required, default: false)',
    type: 'boolean',
  })
  @IsNotEmpty({ message: 'Membership declaration is required' })
  @IsBoolean({ message: 'Membership declaration must be a boolean' })
  osot_membership_declaration: boolean;

  // ========================================
  // LOOKUP FIELDS (at least one required, Account XOR Affiliate)
  // ========================================

  @ApiProperty({
    description:
      'OData bind for Membership Category. Example: "/osot_table_membership_categories(<GUID>)"',
    example:
      '/osot_table_membership_categories/a1b2c3d4-e5f6-7890-abcd-ef1234567890',
    required: false,
  })
  @IsOptional()
  @Allow()
  @Validate(LookupRequiredValidator)
  ['osot_Table_Membership_Category@odata.bind']?: string;

  @ApiProperty({
    description:
      'OData bind for Account. Example: "/osot_table_accounts(<GUID>)". Mutually exclusive with Affiliate.',
    example: '/osot_table_accounts/b1a2c3d4-e5f6-7890-abcd-1234567890ef',
    required: false,
  })
  @IsOptional()
  @Allow()
  @Validate(ExclusiveUserReferencePreferenceValidator)
  ['osot_Table_Account@odata.bind']?: string;

  @ApiProperty({
    description:
      'OData bind for Affiliate. Example: "/osot_table_account_affiliates(<GUID>)". Mutually exclusive with Account.',
    example:
      '/osot_table_account_affiliates/c1a2b3d4-e5f6-7890-abcd-123456789012',
    required: false,
  })
  @IsOptional()
  @Allow()
  ['osot_Table_Account_Affiliate@odata.bind']?: string;

  // ========================================
  // PREFERENCE CHOICE FIELDS (all optional)
  // ========================================

  @ApiProperty({
    example: [ThirdParties.RECRUITMENT, ThirdParties.PRODUCT],
    description: 'Third parties preferences (multi-select, optional)',
    enum: ThirdParties,
    isArray: true,
    required: false,
  })
  @IsOptional()
  @IsArray({ message: 'Third parties must be an array' })
  @IsEnum(ThirdParties, {
    each: true,
    message: 'Each value must be a valid third parties option',
  })
  @Validate(ThirdPartiesValidator)
  osot_third_parties?: ThirdParties[];

  @ApiProperty({
    example: [PracticePromotion.SELF, PracticePromotion.EMPLOYER],
    description: 'Practice promotion preferences (multi-select, optional)',
    enum: PracticePromotion,
    isArray: true,
    required: false,
  })
  @IsOptional()
  @IsArray({ message: 'Practice promotion must be an array' })
  @IsEnum(PracticePromotion, {
    each: true,
    message: 'Each value must be a valid practice promotion option',
  })
  @Validate(PracticePromotionValidator)
  osot_practice_promotion?: PracticePromotion[];

  @ApiProperty({
    example: [
      SearchTools.PROFESSIONAL_NETWORKS,
      SearchTools.POTENTIAL_MENTORING,
    ],
    description: 'Search tools preferences (multi-select, optional)',
    enum: SearchTools,
    isArray: true,
    required: false,
  })
  @IsOptional()
  @IsArray({ message: 'Search tools must be an array' })
  @IsEnum(SearchTools, {
    each: true,
    message: 'Each value must be a valid search tools option',
  })
  @Validate(SearchToolsValidator)
  osot_members_search_tools?: SearchTools[];

  @ApiProperty({
    example: false,
    description: 'Shadowing preference (boolean, optional, default: false)',
    type: 'boolean',
    required: false,
  })
  @IsOptional()
  @IsBoolean({ message: 'Shadowing must be a boolean' })
  @Validate(ShadowingValidator)
  osot_shadowing?: boolean;

  @ApiProperty({
    example: [
      PsychotherapySupervision.COGNITIVE_BEHAVIOURAL,
      PsychotherapySupervision.MINDFULNESS,
    ],
    description:
      'Psychotherapy supervision preferences (multi-select, optional)',
    enum: PsychotherapySupervision,
    isArray: true,
    required: false,
  })
  @IsOptional()
  @IsArray({ message: 'Psychotherapy supervision must be an array' })
  @IsEnum(PsychotherapySupervision, {
    each: true,
    message: 'Each value must be a valid psychotherapy supervision option',
  })
  @Validate(PsychotherapySupervisionValidator)
  osot_psychotherapy_supervision?: PsychotherapySupervision[];

  // ========================================
  // ACCESS CONTROL FIELDS (optional with defaults)
  // ========================================

  @ApiProperty({
    example: Privilege.OWNER,
    description: 'Privilege level from global enum (optional, default: Owner)',
    enum: Privilege,
    required: false,
  })
  @IsOptional()
  @IsEnum(Privilege, { message: 'Must be a valid privilege level' })
  @Validate(PrivilegePreferenceValidator)
  osot_privilege?: Privilege;

  @ApiProperty({
    example: AccessModifier.PRIVATE,
    description:
      'Access modifier from global enum (optional, default: Private)',
    enum: AccessModifier,
    required: false,
  })
  @IsOptional()
  @IsEnum(AccessModifier, { message: 'Must be a valid access modifier' })
  @Validate(AccessModifiersPreferenceValidator)
  osot_access_modifiers?: AccessModifier;

  // ========================================
  // SYSTEM TIMESTAMP FIELDS
  // ========================================

  @ApiProperty({
    example: '2025-01-15T10:30:00Z',
    description: 'Creation timestamp (auto-generated by Dataverse)',
    type: 'string',
    format: 'date-time',
    required: false,
  })
  @IsOptional()
  @Type(() => Date)
  @IsDate({ message: 'Created on must be a valid date' })
  createdon?: Date;

  @ApiProperty({
    example: '2025-01-20T14:45:00Z',
    description: 'Last modification timestamp (auto-managed by Dataverse)',
    type: 'string',
    format: 'date-time',
    required: false,
  })
  @IsOptional()
  @Type(() => Date)
  @IsDate({ message: 'Modified on must be a valid date' })
  modifiedon?: Date;
}
