/**
 * Insurance Provider Validation Constants
 *
 * Business rules and validation constraints for Insurance Provider entity:
 * - Field length limits
 * - Required field rules
 * - Format patterns
 * - Date validations
 *
 * Based on Dataverse schema in table_Insurance_Provider.csv
 */

/**
 * Field length constraints
 */
export const INSURANCE_PROVIDER_FIELD_LENGTH = {
  /**
   * Provider ID (Autonumber)
   * Format: osot-prov-0000001
   * Generated by Dataverse, not user-provided
   */
  PROVIDER_ID_PREFIX: 'osot-prov',
  PROVIDER_ID_SEED: 1,
  PROVIDER_ID_DIGITS: 7,

  /**
   * Text field constraints
   */
  INSURANCE_COMPANY_NAME_MAX: 255,
  INSURANCE_BROKER_NAME_MAX: 255,
  INSURANCE_COMPANY_LOGO_MAX: 1000,
  INSURANCE_BROKER_LOGO_MAX: 1000,
  MASTER_POLICY_DESCRIPTION_MAX: 4000,
  INSURANCE_AUTHORIZED_REPRESENTATIVE_MAX: 1000,
  CERTIFICATE_OBSERVATIONS_MAX: 4000,
  BROKER_GENERAL_INFORMATION_MAX: 4000,

  // Aliases for DTO compatibility (without _MAX suffix)
  INSURANCE_COMPANY_NAME: 255,
  INSURANCE_BROKER_NAME: 255,
  INSURANCE_COMPANY_LOGO: 1000,
  INSURANCE_BROKER_LOGO: 1000,
  MASTER_POLICY_DESCRIPTION: 4000,
  INSURANCE_AUTHORIZED_REPRESENTATIVE: 1000,
  CERTIFICATE_OBSERVATIONS: 4000,
  BROKER_GENERAL_INFORMATION: 4000,
} as const;

/**
 * URL validation pattern for logo and representative URLs
 * Accepts http, https protocols
 */
export const INSURANCE_PROVIDER_URL_PATTERN =
  /^https?:\/\/(www\.)?[-a-zA-Z0-9@:%._+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_+.~#?&/=]*)$/;

/**
 * Date validation rules
 */
export const INSURANCE_PROVIDER_DATE_RULES = {
  /**
   * Policy period end must be after or equal to start
   */
  END_DATE_AFTER_START: true,
} as const;

/**
 * Insurance Provider validation rules
 */
export const INSURANCE_PROVIDER_VALIDATION_RULES = {
  /**
   * Organization is always required (multi-tenant)
   */
  REQUIRES_ORGANIZATION: true,

  /**
   * Required fields for provider identity
   */
  REQUIRES_COMPANY_NAME: true,
  REQUIRES_BROKER_NAME: true,
  REQUIRES_COMPANY_LOGO: true,
  REQUIRES_POLICY_PERIOD_START: true,
  REQUIRES_POLICY_PERIOD_END: true,
  REQUIRES_MASTER_POLICY_DESCRIPTION: true,
  REQUIRES_AUTHORIZED_REPRESENTATIVE: true,
} as const;
