/**
 * Create Organization DTO
 * DTO for organization creation operations with slug validation
 *
 * ESSENTIAL MODULES INTEGRATION:
 * - Inherits all validation from OrganizationBasicDto
 * - Includes comprehensive slug validation (format, uniqueness, reserved words)
 * - Integrates with DataverseService for OData entity creation
 *
 * DATAVERSE INTEGRATION:
 * - Auto-generation of Organization ID (osot-org-0000001 format)
 * - UUID generation for primary key field
 * - Business rule validation during organization creation
 * - System fields are auto-generated and not included in this DTO
 *
 * USAGE CONTEXT:
 * - Organization creation via administrative endpoints
 * - Multi-tenancy setup for new associations
 * - White-label system onboarding
 * - API integration with organization management systems
 *
 * BUSINESS RULES:
 * - Slug is required and must be unique across all organizations
 * - Slug format: lowercase, numbers, hyphens only (^[a-z0-9-]+$)
 * - Slug cannot be a reserved keyword (admin, api, login, etc.)
 * - Slug is immutable after creation (cannot be changed)
 * - All fields from OrganizationBasicDto are validated
 * - Organization status defaults to Active if not provided
 * - Privilege defaults to Main if not provided
 * - Access modifier defaults to Private if not provided
 */

import { ApiProperty } from '@nestjs/swagger';
import {
  IsString,
  IsNotEmpty,
  MaxLength,
  MinLength,
  Matches,
} from 'class-validator';
import { OrganizationBasicDto } from './organization-basic.dto';

// Constants integration
import {
  ORGANIZATION_FIELD_LENGTH,
  SLUG_PATTERN,
  ORGANIZATION_VALIDATION_MESSAGES,
} from '../constants/organization-validation.constant';

// Validators integration (will be created next if needed)
// import { IsSlugUniqueValidator } from '../validators/is-slug-unique.validator';
// import { IsNotReservedSlugValidator } from '../validators/is-not-reserved-slug.validator';

export class CreateOrganizationDto extends OrganizationBasicDto {
  // ========================================
  // SLUG FIELD (required for creation, immutable after)
  // ========================================

  @ApiProperty({
    example: 'osot',
    description:
      'URL-friendly unique identifier (lowercase, numbers, hyphens only). Used in white-label URLs: /login/{slug}. Immutable after creation.',
    pattern: '^[a-z0-9-]+$',
    maxLength: ORGANIZATION_FIELD_LENGTH.SLUG_MAX,
    minLength: ORGANIZATION_FIELD_LENGTH.SLUG_MIN,
  })
  @IsNotEmpty({ message: ORGANIZATION_VALIDATION_MESSAGES.slugRequired })
  @IsString({ message: 'Slug must be a string' })
  @MinLength(ORGANIZATION_FIELD_LENGTH.SLUG_MIN, {
    message: ORGANIZATION_VALIDATION_MESSAGES.slugTooShort,
  })
  @MaxLength(ORGANIZATION_FIELD_LENGTH.SLUG_MAX, {
    message: ORGANIZATION_VALIDATION_MESSAGES.slugTooLong,
  })
  @Matches(SLUG_PATTERN, {
    message: ORGANIZATION_VALIDATION_MESSAGES.slugPattern,
  })
  // TODO: Add custom validators when validator layer is implemented
  // @Validate(IsNotReservedSlugValidator, {
  //   message: ORGANIZATION_VALIDATION_MESSAGES.slugReserved,
  // })
  // @Validate(IsSlugUniqueValidator, {
  //   message: ORGANIZATION_VALIDATION_MESSAGES.slugUnique,
  // })
  osot_slug: string;

  // Note: Fields auto-generated by the system (NOT included in creation requests):
  // - osot_organizationid: Auto-generated with format osot-org-0000001
  // - osot_table_organizationid: System-generated UUID
  // - createdon: System timestamp
  // - modifiedon: System timestamp
  // - ownerid: Set based on authentication context
  // - osot_organization_status: Defaults to AccountStatus.ACTIVE (1)
  // - osot_privilege: Defaults to Privilege.MAIN
  // - osot_access_modifier: Defaults to AccessModifier.PRIVATE
}
