/**
 * Insurance Provider Mapper
 *
 * Bidirectional transformation between DTOs, Internal, and Dataverse formats.
 * Handles:
 * - Date conversions (ISO 8601 strings ↔ Date objects)
 * - Organization relationship binding (OData @odata.bind)
 * - Field normalization (uppercase, formatting)
 * - Access control fields (Privilege, AccessModifier enums)
 * - System fields (read-only autonumbers, timestamps)
 */

import { CreateInsuranceProviderDto } from '../dtos/insurance-provider-create.dto';
import { UpdateInsuranceProviderDto } from '../dtos/insurance-provider-update.dto';
import { InsuranceProviderResponseDto } from '../dtos/insurance-provider-response.dto';
import { InsuranceProviderInternal } from '../interfaces/insurance-provider-internal.interface';
import { InsuranceProviderDataverse } from '../interfaces/insurance-provider-dataverse.interface';
import { INSURANCE_PROVIDER_ACCESS_RULES } from '../constants/insurance-provider-business-rules.constant';

// Export Response DTO type for external use
export { InsuranceProviderResponseDto } from '../dtos/insurance-provider-response.dto';

/**
 * Helper Functions for Data Conversions
 */

/**
 * Convert ISO 8601 string to Date object
 * Handles null/undefined safely
 * Example: '2026-01-23T00:00:00Z' -> Date object
 */
function parseIsoDate(dateString: string | undefined): Date | undefined {
  if (!dateString) return undefined;
  return new Date(dateString);
}

/**
 * Convert Date object to ISO 8601 string
 * Handles null/undefined safely
 * Example: Date object -> '2026-01-23T00:00:00Z'
 */
function toIsoString(date: Date | undefined): string | undefined {
  if (!date) return undefined;
  return date.toISOString();
}

/**
 * Create OData @odata.bind string from GUID
 * Example: "a1b2c3d4-e5f6-7890-abcd-ef1234567890" -> "/osot_table_organizations(a1b2c3d4-e5f6-7890-abcd-ef1234567890)"
 */
function createOdataBind(
  entity: string,
  guid: string | undefined,
): string | undefined {
  if (!guid) return undefined;
  return `/osot_table_${entity}(${guid})`;
}

/**
 * Normalize company/broker names to uppercase (Dataverse business rule)
 */
function normalizeCompanyName(name: string | undefined): string | undefined {
  if (!name) return undefined;
  return name.toUpperCase().trim();
}

/**
 * Insurance Provider Mapper Class
 * Handles bidirectional transformations between DTOs, Internal, and Dataverse formats
 */
export class InsuranceProviderMapper {
  /**
   * Transform CreateInsuranceProviderDto to InsuranceProviderInternal
   *
   * Purpose: Convert API request data to internal domain model
   * Handles: Date parsing, relationship GUIDs, field normalization
   *
   * @param dto - Create request DTO with all required fields
   * @returns InsuranceProviderInternal - Internal domain representation ready for business rules
   */
  static createDtoToInternal(
    dto: CreateInsuranceProviderDto,
  ): InsuranceProviderInternal {
    return {
      // ========================================
      // SYSTEM FIELDS (not set on create, generated by Dataverse)
      // ========================================
      // osot_table_insurance_providerid: undefined, // System-generated GUID
      // osot_provider_id: undefined, // System-generated autonumber (osot-prov-0000001)
      // createdon: undefined, // System timestamp
      // modifiedon: undefined, // System timestamp

      // ========================================
      // REQUIRED RELATIONSHIP FIELD
      // ========================================
      organizationGuid: dto.organizationGuid, // Immutable multi-tenant owner

      // ========================================
      // PROVIDER IDENTIFICATION (required, immutable)
      // ========================================
      osot_insurance_company_name: normalizeCompanyName(
        dto.osot_insurance_company_name,
      ),
      osot_insurance_broker_name: normalizeCompanyName(
        dto.osot_insurance_broker_name,
      ),

      // ========================================
      // LOGOS (required, immutable)
      // ========================================
      osot_insurance_company_logo: dto.osot_insurance_company_logo,
      osot_insurance_broker_logo: dto.osot_insurance_broker_logo,

      // ========================================
      // POLICY PERIOD (required, immutable)
      // ========================================
      osot_policy_period_start: parseIsoDate(dto.osot_policy_period_start),
      osot_policy_period_end: parseIsoDate(dto.osot_policy_period_end),

      // ========================================
      // POLICY DESCRIPTIONS (required, immutable)
      // ========================================
      osot_master_policy_description: dto.osot_master_policy_description,
      osot_insurance_authorized_representative:
        dto.osot_insurance_authorized_representative,

      // ========================================
      // OPTIONAL DESCRIPTIVE FIELDS (immutable)
      // ========================================
      osot_certificate_observations: dto.osot_certificate_observations,
      osot_broker_general_information: dto.osot_broker_general_information,

      // ========================================
      // ACCESS CONTROL (use defaults if not provided)
      // ========================================
      osot_privilege:
        dto.osot_privilege ?? INSURANCE_PROVIDER_ACCESS_RULES.DEFAULT_PRIVILEGE,
      osot_access_modifier:
        dto.osot_access_modifier ??
        INSURANCE_PROVIDER_ACCESS_RULES.DEFAULT_ACCESS_MODIFIER,
    };
  }

  /**
   * Transform Internal InsuranceProviderInternal to Dataverse payload
   *
   * Purpose: Convert domain model to Dataverse OData format
   * Handles: ISO date formatting, OData @odata.bind relationships
   *
   * @param internal - Internal domain representation
   * @returns Partial<InsuranceProviderDataverse> - Payload ready for Dataverse API
   */
  static internalToDataverse(
    internal: Partial<InsuranceProviderInternal>,
  ): Partial<InsuranceProviderDataverse> {
    const dataverse: Partial<InsuranceProviderDataverse> = {
      // ========================================
      // REQUIRED RELATIONSHIP BINDING (OData)
      // ========================================
      'osot_Table_Organization@odata.bind': createOdataBind(
        'organization',
        internal.organizationGuid,
      ),

      // ========================================
      // PROVIDER IDENTIFICATION
      // ========================================
      osot_insurance_company_name: internal.osot_insurance_company_name,
      osot_insurance_broker_name: internal.osot_insurance_broker_name,

      // ========================================
      // LOGOS
      // ========================================
      osot_insurance_company_logo: internal.osot_insurance_company_logo,
      osot_insurance_broker_logo: internal.osot_insurance_broker_logo,

      // ========================================
      // POLICY PERIOD (convert to ISO 8601)
      // ========================================
      osot_policy_period_start: toIsoString(internal.osot_policy_period_start),
      osot_policy_period_end: toIsoString(internal.osot_policy_period_end),

      // ========================================
      // POLICY DESCRIPTIONS
      // ========================================
      osot_master_policy_description: internal.osot_master_policy_description,
      osot_insurance_authorized_representative:
        internal.osot_insurance_authorized_representative,

      // ========================================
      // OPTIONAL DESCRIPTIVE FIELDS
      // ========================================
      osot_certificate_observations: internal.osot_certificate_observations,
      osot_broker_general_information: internal.osot_broker_general_information,

      // ========================================
      // ACCESS CONTROL
      // ========================================
      osot_privilege: internal.osot_privilege,
      osot_access_modifier: internal.osot_access_modifier,
    };

    // Remove undefined values (don't send to Dataverse)
    Object.keys(dataverse).forEach((key) => {
      if (
        dataverse[key as keyof InsuranceProviderDataverse] === undefined ||
        dataverse[key as keyof InsuranceProviderDataverse] === null
      ) {
        delete dataverse[key as keyof InsuranceProviderDataverse];
      }
    });

    return dataverse;
  }

  /**
   * Transform Dataverse response to InsuranceProviderInternal
   *
   * Purpose: Convert Dataverse OData response to internal domain model
   * Handles: Date parsing from ISO strings, relationship GUID extraction
   *
   * @param dataverse - Dataverse API response data
   * @returns InsuranceProviderInternal - Internal domain representation
   */
  static dataverseToInternal(
    dataverse: InsuranceProviderDataverse,
  ): InsuranceProviderInternal {
    return {
      // ========================================
      // SYSTEM FIELDS (from Dataverse response)
      // ========================================
      osot_table_insurance_providerid:
        dataverse.osot_table_insurance_providerid,
      osot_provider_id: dataverse.osot_provider_id,
      createdon: parseIsoDate(dataverse.createdon),
      modifiedon: parseIsoDate(dataverse.modifiedon),
      ownerid: dataverse.ownerid,
      statecode: dataverse.statecode,
      statuscode: dataverse.statuscode,

      // ========================================
      // RELATIONSHIP FIELDS (extract GUID from lookup value)
      // ========================================
      organizationGuid: dataverse._osot_table_organization_value || '',

      // ========================================
      // PROVIDER IDENTIFICATION
      // ========================================
      osot_insurance_company_name: dataverse.osot_insurance_company_name || '',
      osot_insurance_broker_name: dataverse.osot_insurance_broker_name || '',

      // ========================================
      // LOGOS
      // ========================================
      osot_insurance_company_logo: dataverse.osot_insurance_company_logo || '',
      osot_insurance_broker_logo: dataverse.osot_insurance_broker_logo,

      // ========================================
      // POLICY PERIOD (convert from ISO strings)
      // ========================================
      osot_policy_period_start: parseIsoDate(
        dataverse.osot_policy_period_start,
      ),
      osot_policy_period_end: parseIsoDate(dataverse.osot_policy_period_end),

      // ========================================
      // POLICY DESCRIPTIONS
      // ========================================
      osot_master_policy_description:
        dataverse.osot_master_policy_description || '',
      osot_insurance_authorized_representative:
        dataverse.osot_insurance_authorized_representative || '',

      // ========================================
      // OPTIONAL DESCRIPTIVE FIELDS
      // ========================================
      osot_certificate_observations: dataverse.osot_certificate_observations,
      osot_broker_general_information:
        dataverse.osot_broker_general_information,

      // ========================================
      // ACCESS CONTROL
      // ========================================
      osot_privilege: dataverse.osot_privilege,
      osot_access_modifier: dataverse.osot_access_modifier,
    };
  }

  /**
   * Transform UpdateInsuranceProviderDto to Partial InsuranceProviderInternal
   *
   * Purpose: Convert API update request to internal domain model
   * Important: InsuranceProvider fields are mostly immutable after creation
   * All fields can only be updated through admin operations with proper authorization
   *
   * @param dto - Update request DTO (mutable fields only)
   * @returns Partial<InsuranceProviderInternal> - Internal representation for update operation
   */
  static updateDtoToInternal(
    dto: UpdateInsuranceProviderDto,
  ): Partial<InsuranceProviderInternal> {
    const internal: Partial<InsuranceProviderInternal> = {
      // Provider details can be updated (typically by Admin role only)
      osot_insurance_company_name: dto.osot_insurance_company_name
        ? normalizeCompanyName(dto.osot_insurance_company_name)
        : undefined,
      osot_insurance_broker_name: dto.osot_insurance_broker_name
        ? normalizeCompanyName(dto.osot_insurance_broker_name)
        : undefined,
      osot_insurance_company_logo: dto.osot_insurance_company_logo,
      osot_insurance_broker_logo: dto.osot_insurance_broker_logo,
      osot_policy_period_start: dto.osot_policy_period_start
        ? parseIsoDate(dto.osot_policy_period_start)
        : undefined,
      osot_policy_period_end: dto.osot_policy_period_end
        ? parseIsoDate(dto.osot_policy_period_end)
        : undefined,
      osot_master_policy_description: dto.osot_master_policy_description,
      osot_insurance_authorized_representative:
        dto.osot_insurance_authorized_representative,
      osot_certificate_observations: dto.osot_certificate_observations,
      osot_broker_general_information: dto.osot_broker_general_information,

      // Access control can be updated
      osot_privilege: dto.osot_privilege,
      osot_access_modifier: dto.osot_access_modifier,
    };

    // Remove undefined values
    Object.keys(internal).forEach((key) => {
      if (internal[key as keyof InsuranceProviderInternal] === undefined) {
        delete internal[key as keyof InsuranceProviderInternal];
      }
    });

    return internal;
  }

  /**
   * Transform InsuranceProviderInternal to InsuranceProviderResponseDto
   *
   * Purpose: Convert internal domain model to API response
   * Handles: Date serialization, system field exposure, read-only fields
   *
   * @param internal - Internal domain representation
   * @returns InsuranceProviderResponseDto - Response DTO for API output
   */
  static internalToResponseDto(
    internal: InsuranceProviderInternal,
  ): InsuranceProviderResponseDto {
    const response = new InsuranceProviderResponseDto();

    // ========================================
    // SYSTEM FIELDS
    // ========================================
    response.osot_table_insurance_providerid =
      internal.osot_table_insurance_providerid;
    response.osot_provider_id = internal.osot_provider_id;
    response.createdon = toIsoString(internal.createdon);
    response.modifiedon = toIsoString(internal.modifiedon);

    // ========================================
    // RELATIONSHIP FIELDS (GUIDs)
    // ========================================
    response.organizationGuid = internal.organizationGuid;

    // ========================================
    // PROVIDER IDENTIFICATION
    // ========================================
    response.osot_insurance_company_name = internal.osot_insurance_company_name;
    response.osot_insurance_broker_name = internal.osot_insurance_broker_name;

    // ========================================
    // LOGOS
    // ========================================
    response.osot_insurance_company_logo = internal.osot_insurance_company_logo;
    response.osot_insurance_broker_logo = internal.osot_insurance_broker_logo;

    // ========================================
    // POLICY PERIOD (as ISO strings for API)
    // ========================================
    response.osot_policy_period_start = toIsoString(
      internal.osot_policy_period_start,
    );
    response.osot_policy_period_end = toIsoString(
      internal.osot_policy_period_end,
    );

    // ========================================
    // POLICY DESCRIPTIONS
    // ========================================
    response.osot_master_policy_description =
      internal.osot_master_policy_description;
    response.osot_insurance_authorized_representative =
      internal.osot_insurance_authorized_representative;

    // ========================================
    // OPTIONAL DESCRIPTIVE FIELDS
    // ========================================
    response.osot_certificate_observations =
      internal.osot_certificate_observations;
    response.osot_broker_general_information =
      internal.osot_broker_general_information;

    // ========================================
    // ACCESS CONTROL
    // ========================================
    response.osot_privilege = internal.osot_privilege;
    response.osot_access_modifier = internal.osot_access_modifier;

    return response;
  }
}
