/**
 * Create Identity For Account DTO
 *
 * Simplified DTO specifically designed for Account integration workflow.
 * This DTO contains only the essential fields for identity creation during account registration.
 *
 * INTEGRATION PURPOSE:
 * - Identity record creation during account registration
 * - Essential identity fields only
 * - Internal use only - not for direct user access
 *
 * DESIGN PRINCIPLES:
 * - Only essential identity fields
 * - Simple validation
 * - Fast creation for high-volume account registration
 * - Compatible with Dataverse lookups to Account entity
 */

import { ApiProperty } from '@nestjs/swagger';
import {
  IsArray,
  IsOptional,
  IsEnum,
  IsBoolean,
  IsString,
  MaxLength,
  Validate,
  ArrayMinSize,
  ArrayMaxSize,
  Allow,
} from 'class-validator';
import {
  Language,
  Gender,
  Race,
  IndigenousDetail,
} from '../../../../common/enums';
import {
  IdentityChosenNameValidator,
  IdentityLanguagesValidator,
  IdentityIndigenousDetailOtherValidator,
} from '../validators/identity.validators';

export class CreateIdentityForAccountDto {
  // ========================================
  // RELATIONSHIP FIELDS
  // ========================================

  @ApiProperty({
    description:
      'OData bind for Account. Example: "/osot_table_accounts(<GUID>)"',
    example: '/osot_table_accounts/b1a2c3d4-e5f6-7890-abcd-1234567890ef',
    required: false,
  })
  @IsOptional()
  @Allow()
  ['osot_Table_Account@odata.bind']?: string;

  @ApiProperty({
    description:
      'User business ID for account relationship. Will be set automatically by orchestrator.',
    example: 'osot-0000123',
    required: false,
  })
  @IsOptional()
  @IsString()
  osot_user_business_id?: string;

  // ========================================
  // ESSENTIAL IDENTITY FIELDS
  // ========================================
  // Note: osot_user_business_id is auto-generated by Dataverse, not provided by user

  @ApiProperty({
    example: 'Alex',
    description: 'Preferred or chosen name (optional)',
    required: false,
    maxLength: 255,
  })
  @IsOptional()
  @IsString()
  @MaxLength(255)
  @Validate(IdentityChosenNameValidator)
  osot_chosen_name?: string;

  @ApiProperty({
    example: [Language.ENGLISH, Language.FRENCH],
    description: 'Language preferences (at least one required)',
    isArray: true,
    enum: Language,
  })
  @IsArray()
  @IsEnum(Language, { each: true })
  @ArrayMinSize(1, { message: 'At least one language must be selected' })
  @ArrayMaxSize(5, {
    message: 'Maximum 5 languages allowed during account creation',
  })
  @Validate(IdentityLanguagesValidator)
  osot_language: Language[];

  @ApiProperty({
    example: 'Mandarin',
    description:
      'Custom language specification when preferred language not in predefined list (optional)',
    required: false,
    maxLength: 255,
  })
  @IsOptional()
  @IsString()
  @MaxLength(255)
  osot_other_language?: string;

  @ApiProperty({
    example: Gender.PREFER_NOT_TO_DISCLOSE,
    description: 'Gender identity (optional)',
    enum: Gender,
    required: false,
  })
  @IsOptional()
  @IsEnum(Gender)
  osot_gender?: Gender;

  @ApiProperty({
    example: Race.OTHER,
    description: 'Racial identity (optional)',
    enum: Race,
    required: false,
  })
  @IsOptional()
  @IsEnum(Race)
  osot_race?: Race;

  @ApiProperty({
    example: false,
    description: 'Indigenous identity status (optional)',
    required: false,
  })
  @IsOptional()
  @IsBoolean()
  osot_indigenous?: boolean;

  @ApiProperty({
    example: IndigenousDetail.FIRST_NATIONS,
    description:
      'Specific Indigenous identity (optional, requires indigenous=true). Use OTHER (0) if providing custom description.',
    enum: IndigenousDetail,
    required: false,
  })
  @IsOptional()
  @IsEnum(IndigenousDetail)
  osot_indigenous_detail?: IndigenousDetail;

  @ApiProperty({
    example: 'Mohawk Nation',
    description:
      'Other Indigenous identity description (only when indigenous_detail=OTHER)',
    required: false,
    maxLength: 100,
  })
  @IsOptional()
  @IsString()
  @MaxLength(100)
  @Validate(IdentityIndigenousDetailOtherValidator)
  osot_indigenous_detail_other?: string;

  @ApiProperty({
    example: false,
    description: 'Disability status for accommodation purposes (optional)',
    required: false,
  })
  @IsOptional()
  @IsBoolean()
  osot_disability?: boolean;

  // ========================================
  // SYSTEM CONTROLLED FIELDS (NOT INCLUDED)
  // ========================================
  // Note: Access control fields (osot_access_modifiers, osot_privilege)
  // are managed by the system and not included in user creation requests
  // Note: osot_user_business_id is auto-generated by Dataverse
}
