import { ApiProperty } from '@nestjs/swagger';
import {
  IsString,
  IsOptional,
  IsEnum,
  IsBoolean,
  IsArray,
  MaxLength,
  Validate,
  ArrayMinSize,
  ArrayMaxSize,
} from 'class-validator';
import {
  Language,
  Gender,
  Race,
  IndigenousDetail,
} from '../../../../common/enums';
import {
  IdentityChosenNameValidator,
  IdentityLanguagesValidator,
  IdentityIndigenousDetailOtherValidator,
} from '../validators/identity.validators';

/**
 * Identity Registration DTO for user self-registration workflows.
 * Specialized DTO for identity creation during registration process.
 * Used when users create accounts and provide initial identity information.
 *
 * Key characteristics:
 * - Streamlined for registration user experience
 * - Excludes sensitive fields inappropriate for self-registration
 * - Focuses on essential identity information collection
 * - Default privacy settings applied for new users
 * - Cultural identity fields are completely optional
 */
export class IdentityRegistrationDto {
  // Note: osot_user_business_id is auto-generated by Dataverse, not provided by user

  @ApiProperty({
    example: 'Alex',
    description: 'Preferred or chosen name (optional during registration)',
    required: false,
    maxLength: 255,
  })
  @IsOptional()
  @IsString()
  @MaxLength(255)
  @Validate(IdentityChosenNameValidator)
  osot_chosen_name?: string;

  @ApiProperty({
    example: [Language.ENGLISH],
    description: 'Language preferences (at least one required)',
    isArray: true,
    enum: Language,
  })
  @IsArray()
  @IsEnum(Language, { each: true })
  @ArrayMinSize(1, { message: 'Please select at least one language' })
  @ArrayMaxSize(5, {
    message: 'Maximum 5 languages allowed during registration',
  })
  @Validate(IdentityLanguagesValidator)
  osot_language: Language[];

  @ApiProperty({
    example: Gender.PREFER_NOT_TO_DISCLOSE,
    description: 'Gender identity (completely optional)',
    enum: Gender,
    required: false,
  })
  @IsOptional()
  @IsEnum(Gender)
  osot_gender?: Gender;

  @ApiProperty({
    example: Race.OTHER,
    description: 'Racial identity (completely optional)',
    enum: Race,
    required: false,
  })
  @IsOptional()
  @IsEnum(Race)
  osot_race?: Race;

  @ApiProperty({
    example: false,
    description: 'Indigenous identity status (completely optional)',
    required: false,
  })
  @IsOptional()
  @IsBoolean()
  osot_indigenous?: boolean;

  @ApiProperty({
    example: IndigenousDetail.FIRST_NATIONS,
    description: 'Specific Indigenous identity (optional)',
    enum: IndigenousDetail,
    required: false,
  })
  @IsOptional()
  @IsEnum(IndigenousDetail)
  osot_indigenous_detail?: IndigenousDetail;

  @ApiProperty({
    example: 'Mohawk Nation',
    description: 'Other Indigenous identity description (optional)',
    required: false,
    maxLength: 100,
  })
  @IsOptional()
  @IsString()
  @MaxLength(100)
  @Validate(IdentityIndigenousDetailOtherValidator)
  osot_indigenous_detail_other?: string;

  @ApiProperty({
    example: false,
    description: 'Disability status for accommodation (completely optional)',
    required: false,
  })
  @IsOptional()
  @IsBoolean()
  osot_disability?: boolean;
}

/**
 * Usage notes:
 * - Designed specifically for user registration workflows
 * - Language selection is required but limited to 5 maximum for simplicity
 * - All cultural identity fields are optional to respect user comfort levels
 * - Cultural consistency validation ensures related fields are logical
 * - Registration process should not overwhelm users with too many fields
 * - Additional identity details can be added post-registration via update endpoints
 */
