import { ApiProperty } from '@nestjs/swagger';
import {
  IsString,
  IsOptional,
  IsEnum,
  IsBoolean,
  IsArray,
  MaxLength,
  Validate,
  ArrayMinSize,
  ArrayMaxSize,
  Allow,
} from 'class-validator';
import {
  Language,
  Gender,
  Race,
  IndigenousDetail,
} from '../../../../common/enums';
import {
  IdentityChosenNameValidator,
  IdentityLanguagesValidator,
  IdentityIndigenousDetailOtherValidator,
} from '../validators/identity.validators';

/**
 * Basic Identity DTO for common identity data operations.
 * Contains essential identity fields without sensitive internal data.
 * Used for creating, updating, and displaying basic identity information.
 * Note: osot_user_business_id is auto-generated by Dataverse, not provided by user.
 */
export class IdentityBasicDto {
  // ========================================
  // RELATIONSHIP FIELDS
  // ========================================

  @ApiProperty({
    description:
      'OData bind for Account. Example: "/osot_table_accounts(<GUID>)"',
    example: '/osot_table_accounts/b1a2c3d4-e5f6-7890-abcd-1234567890ef',
    required: false,
  })
  @IsOptional()
  @Allow()
  ['osot_Table_Account@odata.bind']?: string;

  // ========================================
  // IDENTITY FIELDS
  // ========================================

  @ApiProperty({
    example: 'Alex',
    description: 'Preferred or chosen name (optional)',
    required: false,
    maxLength: 255,
  })
  @IsOptional()
  @IsString()
  @MaxLength(255)
  @Validate(IdentityChosenNameValidator)
  osot_chosen_name?: string;

  @ApiProperty({
    example: [Language.ENGLISH, Language.FRENCH],
    description: 'Language preferences (business required, multiple choice)',
    isArray: true,
    enum: Language,
  })
  @IsArray()
  @IsEnum(Language, { each: true })
  @ArrayMinSize(1, { message: 'At least one language must be selected' })
  @ArrayMaxSize(10, { message: 'Maximum 10 languages allowed' })
  @Validate(IdentityLanguagesValidator)
  osot_language: Language[];

  @ApiProperty({
    example: 'Mandarin',
    description: 'Other language not in predefined list (optional)',
    required: false,
    maxLength: 255,
  })
  @IsOptional()
  @IsString()
  @MaxLength(255)
  osot_other_language?: string;

  @ApiProperty({
    example: Gender.PREFER_NOT_TO_DISCLOSE,
    description: 'Gender identity (optional)',
    enum: Gender,
    required: false,
  })
  @IsOptional()
  @IsEnum(Gender)
  osot_gender?: Gender;

  @ApiProperty({
    example: Race.OTHER,
    description: 'Racial identity (optional)',
    enum: Race,
    required: false,
  })
  @IsOptional()
  @IsEnum(Race)
  osot_race?: Race;

  @ApiProperty({
    example: false,
    description: 'Indigenous identity status (optional)',
    required: false,
  })
  @IsOptional()
  @IsBoolean()
  osot_indigenous?: boolean;

  @ApiProperty({
    example: IndigenousDetail.FIRST_NATIONS,
    description:
      'Specific Indigenous identity (optional, requires indigenous=true)',
    enum: IndigenousDetail,
    required: false,
  })
  @IsOptional()
  @IsEnum(IndigenousDetail)
  osot_indigenous_detail?: IndigenousDetail;

  @ApiProperty({
    example: 'Mohawk Nation',
    description: 'Other Indigenous identity description (optional)',
    required: false,
    maxLength: 100,
  })
  @IsOptional()
  @IsString()
  @MaxLength(100)
  @Validate(IdentityIndigenousDetailOtherValidator)
  osot_indigenous_detail_other?: string;

  @ApiProperty({
    example: false,
    description: 'Disability status for accommodation purposes (optional)',
    required: false,
  })
  @IsOptional()
  @IsBoolean()
  osot_disability?: boolean;
}

/**
 * Usage notes:
 * - This DTO is used for basic identity operations where sensitive internal fields are not needed
 * - Language field supports multiple selections (1-10 languages)
 * - Cultural identity fields (race, indigenous) are optional and respect user privacy
 * - Cultural consistency validation ensures Indigenous fields are properly related
 * - All optional fields can be omitted and will use appropriate defaults
 */
