/**
 * Create Membership Settings DTO
 * Simplified version with only user-provided fields for creation operations
 *
 * ESSENTIAL MODULES INTEGRATION:
 * - Includes comprehensive business rule validation for creation workflow
 * - Integrates with DataverseService for OData entity creation
 * - Only includes fields that users should provide in requests
 *
 * DATAVERSE INTEGRATION:
 * - Auto-generation of Settings ID (osot-set-0000001 format)
 * - UUID generation for primary key field
 * - Business rule validation during membership settings creation
 * - System fields are auto-generated and not included in this DTO
 *
 * USAGE CONTEXT:
 * - Membership settings creation via administrative endpoints
 * - Annual membership configuration setup
 * - API integration with membership management systems
 *
 * BUSINESS RULES:
 * - Membership year is required and must be valid (4-character string)
 * - Membership group is required (Individual for account, Business for affiliate)
 * - Year start date is required and must be valid date
 * - Year end date is required and must be after start date
 * - Status is required and must be valid (Active, Inactive, Pending)
 * - Group-year combination must be unique (validated at service layer)
 */

import { ApiProperty } from '@nestjs/swagger';
import {
  IsString,
  IsNotEmpty,
  IsDateString,
  IsEnum,
  Validate,
} from 'class-validator';

// Essential modules integration
import { AccountStatus } from '../../../../common/enums';
import { MembershipGroup } from '../enums/membership-group.enum';

// Membership settings validators integration
import {
  MembershipYearValidator,
  MembershipYearStatusValidator,
} from '../validators/membership-settings.validators';

export class CreateMembershipSettingsDto {
  // ========================================
  // BUSINESS REQUIRED FIELDS (from CSV)
  // ========================================

  @ApiProperty({
    example: '2025',
    description:
      'Membership year as text (CSV: Single line of text, changed from Choice)',
    type: 'string',
    maxLength: 4,
  })
  @IsNotEmpty({ message: 'Membership year is required' })
  @IsString({ message: 'Membership year must be a string' })
  @Validate(MembershipYearValidator)
  osot_membership_year: string;

  // Note: organizationGuid is NOT included in creation requests
  // It is automatically populated from the authenticated user's JWT context
  // The service layer adds it during the creation process via organizationGuid from JWT

  @ApiProperty({
    example: 1, // ACTIVE
    description: 'Membership year status from Choices_Status',
    enum: AccountStatus,
  })
  @IsNotEmpty({ message: 'Membership year status is required' })
  @IsEnum(AccountStatus, { message: 'Must be a valid account status' })
  @Validate(MembershipYearStatusValidator)
  osot_membership_year_status: AccountStatus;

  @ApiProperty({
    example: 1, // INDIVIDUAL
    description:
      'Membership group from Choices_Membership_Group (Individual or Business)',
    enum: MembershipGroup,
  })
  @IsNotEmpty({ message: 'Membership group is required' })
  @IsEnum(MembershipGroup, { message: 'Must be a valid membership group' })
  osot_membership_group: MembershipGroup;

  @ApiProperty({
    example: '2025-01-01',
    description: 'Membership year start date (Date only format)',
    format: 'date',
  })
  @IsNotEmpty({ message: 'Year start date is required' })
  @IsDateString({}, { message: 'Must be a valid date string' })
  osot_year_starts: string;

  @ApiProperty({
    example: '2025-12-31',
    description: 'Membership year end date (Date only format)',
    format: 'date',
  })
  @IsNotEmpty({ message: 'Year end date is required' })
  @IsDateString({}, { message: 'Must be a valid date string' })
  osot_year_ends: string;

  // Note: Fields auto-generated by the system (NOT included in creation requests):
  // - osot_settingsid: Auto-generated with format osot-set-0000001
  // - osot_table_membership_settingid: System-generated UUID
  // - createdon: System timestamp
  // - modifiedon: System timestamp
  // - ownerid: Set based on authentication context
  // - osot_privilege: Default to Privilege.MAIN if not provided
  // - osot_access_modifiers: Default to AccessModifier.PROTECTED if not provided
}
