/**
 * Insurance Internal Interface
 *
 * Internal representation of Insurance entity within the application.
 * Used throughout services, business rules, and mappers.
 *
 * Architecture Notes:
 * - camelCase naming (TypeScript convention)
 * - Native TypeScript types (Date, number, string, boolean)
 * - organizationGuid, orderGuid, accountGuid represent relationships
 * - All snapshot fields are immutable after creation
 * - Some fields (status) are mutable for lifecycle management
 */

import { InsuranceStatus } from '../enum/insurance-status.enum';

/**
 * Insurance entity - Internal representation
 *
 * Represents an insurance certificate with immutable snapshot of insured person,
 * coverage details, and related information frozen at time of policy creation.
 */
export interface InsuranceInternal {
  // ========================================
  // SYSTEM FIELDS
  // ========================================

  /**
   * Unique identifier (GUID/UUID)
   * Example: 'abc-123-def-456-ghi'
   */
  osot_table_insuranceid?: string;

  /**
   * Autonumber ID (human-readable)
   * Example: 'osot-ins-0000001'
   * Read-only, generated by Dataverse
   */
  osot_insuranceid?: string;

  /**
   * Record creation timestamp
   */
  createdon?: Date;

  /**
   * Last modification timestamp
   */
  modifiedon?: Date;

  /**
   * Owner ID (user who owns the record)
   */
  ownerid?: string;

  /**
   * State code (0 = Active, 1 = Inactive)
   */
  statecode?: number;

  /**
   * Status code (detailed status)
   */
  statuscode?: number;

  // ========================================
  // REQUIRED RELATIONSHIP FIELDS (Immutable)
  // ========================================

  /**
   * Organization GUID (required)
   * Represents the sponsoring/governing organization
   * Multi-tenant isolation - data belongs to one organization only
   * Immutable - cannot change after creation
   * Example: 'org-guid-123'
   */
  organizationGuid: string;

  /**
   * Order GUID (required)
   * Represents the parent order that triggered this insurance
   * Reference to the purchase order
   * Immutable - cannot change after creation
   * Example: 'order-guid-456'
   */
  orderGuid: string;

  /**
   * Account/User GUID (required)
   * Represents the insured person
   * Reference to the account being insured
   * Immutable - cannot change after creation
   * Example: 'account-guid-789'
   */
  accountGuid: string;

  // ========================================
  // SNAPSHOT FIELDS FROM ACCOUNT/ADDRESS (14 required - IMMUTABLE)
  // ========================================

  /**
   * Account group (copied from table_account)
   * Classification of the insured account
   * Immutable - frozen at insurance creation
   * Example: 'Individual', 'Organization'
   */
  osot_account_group: string;

  /**
   * Category (copied from membership_category)
   * Professional category/type
   * Immutable - frozen at insurance creation
   * Example: 'OT' (Occupational Therapist), 'OTA' (OT Assistant)
   */
  osot_category: string;

  /**
   * Membership (copied from membership_category)
   * Membership type/tier
   * Immutable - frozen at insurance creation
   * Example: 'Standard', 'Premium', 'Emeritus'
   */
  osot_membership: string;

  /**
   * Membership year (academic year) when insurance was purchased
   * Copied from membership_settings.osot_membership_year
   * Used to determine when certificate expires
   * Immutable - frozen at insurance creation
   * Example: '2025', '2026'
   * Used by scheduler: if osot_membership_year < current_year, status = EXPIRED
   */
  osot_membership_year: string;

  /**
   * Certificate ID (copied from table_account.account_id)
   * Unique identifier for insured person in system
   * Immutable - frozen at insurance creation
   * Used for certificate identification and verification
   */
  osot_certificate: string;

  /**
   * First name (copied from table_account)
   * Given name of insured person
   * Immutable - frozen at insurance creation
   * Max 100 characters
   */
  osot_first_name: string;

  /**
   * Last name (copied from table_account)
   * Family name of insured person
   * Immutable - frozen at insurance creation
   * Max 100 characters
   */
  osot_last_name: string;

  /**
   * Personal/Corporation name (optional)
   * Business name or formal entity name if applicable
   * Immutable - frozen at insurance creation
   * Max 255 characters
   */
  osot_personal_corporation?: string;

  /**
   * Address line 1 (copied from table_address)
   * Street address or primary address line
   * Immutable - frozen at insurance creation
   * Max 255 characters
   */
  osot_address_1: string;

  /**
   * Address line 2 (optional)
   * Secondary address line (suite, unit, etc.)
   * Immutable - frozen at insurance creation
   * Max 255 characters
   */
  osot_address_2?: string;

  /**
   * City (copied from table_address)
   * Municipality of residence/business
   * Immutable - frozen at insurance creation
   * Max 255 characters
   */
  osot_city: string;

  /**
   * Province (copied from table_address)
   * Province/state code
   * Immutable - frozen at insurance creation
   * Example: 'ON', 'BC', 'QC'
   * Max 100 characters
   */
  osot_province: string;

  /**
   * Postal code (copied from table_address)
   * Postal/ZIP code without formatting
   * Immutable - frozen at insurance creation
   * Stored as 'K1A0A6' (no spaces)
   * Max 7 characters
   */
  osot_postal_code: string;

  /**
   * Phone number (copied from table_account.mobile_phone)
   * Contact telephone number
   * Immutable - frozen at insurance creation
   * Max 14 characters
   */
  osot_phone_number: string;

  /**
   * Email (copied from table_account)
   * Contact email address
   * Immutable - frozen at insurance creation
   * Max 255 characters
   */
  osot_email: string;

  // ========================================
  // INSURANCE DETAILS (6 required, 1 optional)
  // ========================================

  /**
   * Insurance type (copied from product name)
   * Type/name of insurance coverage
   * Immutable - frozen at insurance creation
   * Example: 'Professional Liability', 'General Liability'
   * Max 255 characters
   */
  osot_insurance_type: string;

  /**
   * Insurance limit amount (copied from product)
   * Maximum coverage amount provided
   * Immutable - frozen at insurance creation
   * Currency (CAD): 0.00 to 922,337,203,685,477.00
   * Example: 50000.00, 100000.00, 250000.00, 500000.00
   * Precision: 2 decimal places
   */
  osot_insurance_limit: number;

  /**
   * Insurance price (copied from product selected_price)
   * Premium/cost of insurance at purchase time
   * Immutable - frozen at insurance creation
   * Currency (CAD): 0.00 to 922,337,203,685,477.00
   * Example: 79.00, 125.50, 199.99
   * Precision: 2 decimal places
   */
  osot_insurance_price: number;

  /**
   * Insurance total (copied from order_product item_total)
   * Final amount including tax
   * Immutable - frozen at insurance creation
   * Currency (CAD): 0.00 to 922,337,203,685,477.00
   * Example: 89.27 (79.00 + 10.27 tax)
   * Precision: 2 decimal places
   */
  osot_total: number;

  /**
   * Insurance status (lifecycle state)
   * DRAFT (1), PENDING (2), ACTIVE (3), EXPIRED (4), CANCELLED (5)
   * Mutable - changes based on lifecycle events
   * Initial value: PENDING (for automatic creation) or DRAFT (for manual)
   */
  osot_insurance_status: InsuranceStatus;

  /**
   * Insurance declaration (boolean)
   * User declares that all information is true and complete
   * Business required - must be true to create/activate insurance
   * Immutable - set once at creation, not changed after
   */
  osot_insurance_declaration: boolean;

  // ========================================
  // DATE FIELDS (2 required, 1 optional - IMMUTABLE for most)
  // ========================================

  /**
   * Effective date (immutable)
   * When coverage starts and becomes active
   * Typically set to order creation date
   * Cannot be in the future
   * Immutable - frozen at insurance creation
   */
  osot_effective_date: Date;

  /**
   * Expiry date (immutable)
   * When coverage ends automatically
   * Typically 12 months from effective date
   * Immutable - frozen at insurance creation
   */
  osot_expires_date: Date;

  /**
   * Endorsement effective date (optional, immutable)
   * When policy amendment/modification takes effect
   * Null unless endorsement has been applied
   * Immutable - cannot be changed after set
   */
  osot_endorsement_effective_date?: Date;

  // ========================================
  // QUESTIONS & ENDORSEMENTS (6 optional)
  // ========================================

  /**
   * Insurance question 1: Allegations of negligence (boolean)
   * "In the past, has the Applicant or any of his/her employees ever been the
   * recipient of any allegations of professional negligence in writing or verbally?"
   * Optional - default: false
   * High-risk question - true answer triggers manual review
   * Immutable - cannot be changed after initial submission
   */
  osot_insurance_question_1?: boolean;

  /**
   * Explanation for question 1 (optional text)
   * Required if question_1 = true
   * Max 4000 characters
   * Immutable - cannot be changed after initial submission
   */
  osot_insurance_question_1_explain?: string;

  /**
   * Insurance question 2: Insurer cancellation/denial (boolean)
   * "Has any insurer ever declined, cancelled or imposed special conditions
   * for any coverage for you or your entity in the past?"
   * Optional - default: false
   * High-risk question - true answer triggers manual review
   * Immutable - cannot be changed after initial submission
   */
  osot_insurance_question_2?: boolean;

  /**
   * Explanation for question 2 (optional text)
   * Required if question_2 = true
   * Max 4000 characters
   * Immutable - cannot be changed after initial submission
   */
  osot_insurance_question_2_explain?: string;

  /**
   * Insurance question 3: Awareness of potential claims (boolean)
   * "Is the Applicant or any of his/her employees aware of any facts, circumstances
   * or situations which may reasonably give rise to a claim, other than advised above?"
   * Optional - default: false
   * High-risk question - true answer triggers manual review
   * Immutable - cannot be changed after initial submission
   */
  osot_insurance_question_3?: boolean;

  /**
   * Explanation for question 3 (optional text)
   * Required if question_3 = true
   * Max 4000 characters
   * Immutable - cannot be changed after initial submission
   */
  osot_insurance_question_3_explain?: string;

  /**
   * Endorsement description (optional text)
   * Description of policy amendment/modification
   * Max 4000 characters
   * Admin-only field
   * Null unless endorsement has been added
   * Immutable - cannot be changed after effective date passes
   */
  osot_endorsement_description?: string;

  // ========================================
  // ACCESS CONTROL (2 optional fields)
  // ========================================

  /**
   * Privilege level (number)
   * Determines access level to insurance data
   * Optional - defaults to Private
   * May be mutable for administrative changes
   */
  osot_privilege?: number;

  /**
   * Access modifier (number)
   * Determines who can access this insurance
   * Optional - defaults to Private
   * May be mutable for administrative changes
   */
  osot_access_modifiers?: number;
}
