/**
 * Basic Membership Practices DTO
 * Complete version with all fields including system-generated ones
 *
 * ESSENTIAL MODULES INTEGRATION:
 * - Base DTO used by Update operations and internal services
 * - Includes complete business rule validation for all fields
 * - Integrates with DataverseService for full entity management
 * - Contains both user-provided and system-generated fields
 *
 * DATAVERSE INTEGRATION:
 * - Practice ID format: osot-pra-0000001 (auto-generated)
 * - UUID primary key (osot_table_membership_practiceid)
 * - System timestamps (createdon, modifiedon)
 * - Optional lookup relationship (Account) with @odata.bind pattern
 * - Complete OData entity representation
 *
 * USAGE CONTEXT:
 * - Extended by Update DTO for PATCH operations
 * - Internal service layer processing
 * - Mapping between Dataverse and Internal representations
 * - Full entity state management
 *
 * BUSINESS RULES:
 * - All user-provided fields follow same validation as Create DTO
 * - System fields are read-only in normal operations
 * - Practice ID must follow osot-pra-NNNNNNN format
 * - Table must be "osot_table_membership_practice"
 * - osot_membership_year is system-defined from membership-settings
 * - Timestamps managed by Dataverse
 */

import { ApiProperty } from '@nestjs/swagger';
import {
  IsString,
  IsNotEmpty,
  IsOptional,
  IsEnum,
  IsBoolean,
  IsDate,
  IsUUID,
  IsArray,
  MaxLength,
  ArrayMinSize,
  Matches,
} from 'class-validator';
import { Type } from 'class-transformer';

// Global enums integration
import { AccessModifier, Privilege } from '../../../../common/enums';

// Local enums integration
import { ClientsAge } from '../enums/clients-age.enum';
import { PracticeArea } from '../enums/practice-area.enum';
import { PracticeServices } from '../enums/practice-services.enum';
import { PracticeSettings } from '../enums/practice-settings.enum';

export class MembershipPracticesBasicDto {
  // ========================================
  // SYSTEM PRIMARY KEY FIELD
  // ========================================

  @ApiProperty({
    example: 'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
    description:
      'Unique UUID primary key (auto-generated by Dataverse, optional for create)',
    type: 'string',
    format: 'uuid',
    required: false,
  })
  @IsOptional()
  @IsUUID('4', { message: 'Practice ID must be a valid UUID v4' })
  osot_table_membership_practiceid?: string;

  // ========================================
  // SYSTEM IDENTIFIER FIELD
  // ========================================

  @ApiProperty({
    example: 'osot-pra-0000001',
    description:
      'Business identifier (auto-generated, format: osot-pra-NNNNNNN, optional for create)',
    type: 'string',
    required: false,
  })
  @IsOptional()
  @IsString({ message: 'Practice identifier must be a string' })
  @Matches(/^osot-pra-\d{7}$/, {
    message: 'Practice identifier must follow format osot-pra-NNNNNNN',
  })
  osot_practice_id?: string;

  // ========================================
  // SYSTEM TABLE NAME FIELD
  // ========================================

  @ApiProperty({
    example: 'osot_table_membership_practice',
    description:
      'Table name (read-only system field, always "osot_table_membership_practice")',
    type: 'string',
    required: false,
    readOnly: true,
  })
  @IsOptional()
  @IsString({ message: 'Table name must be a string' })
  osot_table_name?: string;

  // ========================================
  // MEMBERSHIP YEAR (SYSTEM-DEFINED)
  // ========================================

  @ApiProperty({
    example: '2026',
    description:
      'Membership year (SYSTEM-DEFINED from membership-settings, immutable after creation)',
    type: 'string',
    readOnly: true,
  })
  @IsNotEmpty({ message: 'Membership year is required' })
  @Matches(/^\d{4}$/, { message: 'Membership year must be in YYYY format' })
  osot_membership_year: string;

  // ========================================
  // USER LOOKUP (OPTIONAL ACCOUNT)
  // ========================================

  @ApiProperty({
    example: 'accounts(b1a2c3d4-e5f6-7890-abcd-1234567890ef)',
    description: 'Account lookup reference (optional)',
    type: 'string',
    required: false,
  })
  @IsOptional()
  @IsString({ message: 'Account reference must be a string' })
  'osot_Table_Account@odata.bind'?: string;

  // ========================================
  // PRECEPTOR DECLARATION
  // ========================================

  @ApiProperty({
    example: false,
    description: 'Preceptor declaration (optional, default: false)',
    type: 'boolean',
    required: false,
  })
  @IsOptional()
  @IsBoolean({ message: 'Preceptor declaration must be a boolean' })
  osot_preceptor_declaration?: boolean;

  // ========================================
  // CLIENTS AGE (MULTIPLE CHOICE - REQUIRED)
  // ========================================

  @ApiProperty({
    example: [ClientsAge.ADULT, ClientsAge.OLDER],
    description:
      'Client age groups served (multi-select, required - minimum 1 value)',
    enum: ClientsAge,
    isArray: true,
  })
  @IsNotEmpty({ message: 'Clients age is required' })
  @IsArray({ message: 'Clients age must be an array' })
  @ArrayMinSize(1, { message: 'Clients age must have at least one value' })
  @IsEnum(ClientsAge, {
    each: true,
    message: 'Each client age must be a valid ClientsAge enum value',
  })
  osot_clients_age: ClientsAge[];

  // ========================================
  // PRACTICE AREA (MULTIPLE CHOICE - OPTIONAL)
  // ========================================

  @ApiProperty({
    example: [PracticeArea.CHRONIC_PAIN, PracticeArea.STROKE],
    description: 'Practice areas (multi-select, optional)',
    enum: PracticeArea,
    isArray: true,
    required: false,
  })
  @IsOptional()
  @IsArray({ message: 'Practice area must be an array' })
  @IsEnum(PracticeArea, {
    each: true,
    message: 'Each practice area must be a valid PracticeArea enum value',
  })
  osot_practice_area?: PracticeArea[];

  // ========================================
  // PRACTICE SETTINGS (MULTIPLE CHOICE - OPTIONAL)
  // ========================================

  @ApiProperty({
    example: [PracticeSettings.CLIENTS_HOME, PracticeSettings.GENERAL_HOSPITAL],
    description: 'Practice settings (multi-select, optional)',
    enum: PracticeSettings,
    isArray: true,
    required: false,
  })
  @IsOptional()
  @IsArray({ message: 'Practice settings must be an array' })
  @IsEnum(PracticeSettings, {
    each: true,
    message:
      'Each practice setting must be a valid PracticeSettings enum value',
  })
  osot_practice_settings?: PracticeSettings[];

  @ApiProperty({
    example: 'Mobile clinic',
    description:
      'Other practice setting description (optional, required when practice_settings contains OTHER, max 255 chars)',
    type: 'string',
    required: false,
    maxLength: 255,
  })
  @IsOptional()
  @IsString({ message: 'Practice settings other must be a string' })
  @MaxLength(255, {
    message: 'Practice settings other must not exceed 255 characters',
  })
  osot_practice_settings_other?: string;

  // ========================================
  // PRACTICE SERVICES (MULTIPLE CHOICE - OPTIONAL)
  // ========================================

  @ApiProperty({
    example: [
      PracticeServices.COGNITIVE_BEHAVIOUR_THERAPY,
      PracticeServices.PAIN_MANAGEMENT,
    ],
    description: 'Practice services offered (multi-select, optional)',
    enum: PracticeServices,
    isArray: true,
    required: false,
  })
  @IsOptional()
  @IsArray({ message: 'Practice services must be an array' })
  @IsEnum(PracticeServices, {
    each: true,
    message:
      'Each practice service must be a valid PracticeServices enum value',
  })
  osot_practice_services?: PracticeServices[];

  @ApiProperty({
    example: 'Specialized pediatric assessment',
    description:
      'Other practice service description (optional, required when practice_services contains OTHER, max 255 chars)',
    type: 'string',
    required: false,
    maxLength: 255,
  })
  @IsOptional()
  @IsString({ message: 'Practice services other must be a string' })
  @MaxLength(255, {
    message: 'Practice services other must not exceed 255 characters',
  })
  osot_practice_services_other?: string;

  // ========================================
  // ACCESS CONTROL FIELDS (SYSTEM-MANAGED)
  // ========================================

  @ApiProperty({
    example: Privilege.OWNER,
    description: 'Privilege level (system-managed, default: OWNER)',
    enum: Privilege,
    required: false,
    readOnly: true,
  })
  @IsOptional()
  @IsEnum(Privilege, {
    message: 'Privilege must be a valid Privilege enum value',
  })
  osot_privilege?: Privilege;

  @ApiProperty({
    example: AccessModifier.PRIVATE,
    description: 'Access modifier (system-managed, default: PRIVATE)',
    enum: AccessModifier,
    required: false,
    readOnly: true,
  })
  @IsOptional()
  @IsEnum(AccessModifier, {
    message: 'Access modifier must be a valid AccessModifier enum value',
  })
  osot_access_modifiers?: AccessModifier;

  // ========================================
  // SYSTEM AUDIT FIELDS
  // ========================================

  @ApiProperty({
    example: '2025-11-27T10:00:00Z',
    description: 'Created timestamp (auto-generated by Dataverse)',
    type: 'string',
    format: 'date-time',
    required: false,
    readOnly: true,
  })
  @IsOptional()
  @Type(() => Date)
  @IsDate({ message: 'Created date must be a valid date' })
  createdon?: Date;

  @ApiProperty({
    example: '2025-11-27T15:30:00Z',
    description: 'Modified timestamp (auto-updated by Dataverse)',
    type: 'string',
    format: 'date-time',
    required: false,
    readOnly: true,
  })
  @IsOptional()
  @Type(() => Date)
  @IsDate({ message: 'Modified date must be a valid date' })
  modifiedon?: Date;

  @ApiProperty({
    example: 'd1e2f3a4-b5c6-7890-abcd-ef1234567890',
    description: 'Owner GUID (system-managed)',
    type: 'string',
    format: 'uuid',
    required: false,
    readOnly: true,
  })
  @IsOptional()
  @IsUUID('4', { message: 'Owner ID must be a valid UUID v4' })
  ownerid?: string;
}
