/**
 * Basic Membership Employment DTO
 * Complete version with all fields including system-generated ones
 *
 * ESSENTIAL MODULES INTEGRATION:
 * - Base DTO used by Update operations and internal services
 * - Includes complete business rule validation for all fields
 * - Integrates with DataverseService for full entity management
 * - Contains both user-provided and system-generated fields
 *
 * DATAVERSE INTEGRATION:
 * - Employment ID format: osot-emp-0000001 (auto-generated)
 * - UUID primary key (osot_employment_id)
 * - System timestamps (createdon, modifiedon)
 * - Two lookup relationships (Account XOR Affiliate) with @odata.bind patterns
 * - Complete OData entity representation
 *
 * USAGE CONTEXT:
 * - Extended by Update DTO for PATCH operations
 * - Internal service layer processing
 * - Mapping between Dataverse and Internal representations
 * - Full entity state management
 *
 * BUSINESS RULES:
 * - All user-provided fields follow same validation as Create DTO
 * - System fields are read-only in normal operations
 * - Employment ID must follow osot-emp-NNNNNNN format
 * - Table must be "osot_table_membership_employment"
 * - osot_membership_year is system-defined from membership-settings
 * - Timestamps managed by Dataverse
 */

import { ApiProperty } from '@nestjs/swagger';
import {
  IsString,
  IsNotEmpty,
  IsOptional,
  IsEnum,
  IsBoolean,
  IsDate,
  IsUUID,
  IsArray,
  IsInt,
  MaxLength,
} from 'class-validator';
import { Type } from 'class-transformer';

// Global enums integration
import { Privilege, AccessModifier } from '../../../../common/enums';

// Local enums integration
import { EmploymentStatus } from '../enums/employment-status.enum';
import { WorkHours } from '../enums/work-hours.enum';
import { RoleDescription } from '../enums/role-descriptor.enum';
import { PracticeYears } from '../enums/practice-years.enum';
import { Funding } from '../enums/funding.enum';
import { Benefits } from '../enums/benefits.enum';
import { HourlyEarnings } from '../enums/hourly-earnings.enum';

export class MembershipEmploymentBasicDto {
  // ========================================
  // SYSTEM PRIMARY KEY FIELD
  // ========================================

  @ApiProperty({
    example: 'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
    description:
      'Unique UUID primary key (auto-generated by Dataverse, optional for create)',
    type: 'string',
    format: 'uuid',
    required: false,
  })
  @IsOptional()
  @IsUUID('4', { message: 'Employment ID must be a valid UUID v4' })
  osot_employment_id?: string;

  // ========================================
  // SYSTEM IDENTIFIER FIELD
  // ========================================

  @ApiProperty({
    example: 'osot-emp-0000001',
    description:
      'Business identifier (auto-generated, format: osot-emp-NNNNNNN, optional for create)',
    type: 'string',
    required: false,
  })
  @IsOptional()
  @IsString({ message: 'Employment identifier must be a string' })
  osot_employment_identifier?: string;

  // ========================================
  // SYSTEM TABLE NAME FIELD
  // ========================================

  @ApiProperty({
    example: 'osot_table_membership_employment',
    description:
      'Table name (read-only system field, always "osot_table_membership_employment")',
    type: 'string',
    required: false,
    readOnly: true,
  })
  @IsOptional()
  @IsString({ message: 'Table name must be a string' })
  osot_table_name?: string;

  // ========================================
  // MEMBERSHIP YEAR (SYSTEM-DEFINED)
  // ========================================

  @ApiProperty({
    example: 2025,
    description:
      'Membership year (SYSTEM-DEFINED from membership-settings, immutable after creation)',
    type: 'integer',
    readOnly: true,
  })
  @IsNotEmpty({ message: 'Membership year is required' })
  @IsInt({ message: 'Membership year must be an integer' })
  osot_membership_year: number;

  // ========================================
  // USER LOOKUPS (ACCOUNT XOR AFFILIATE)
  // ========================================

  @ApiProperty({
    example: 'accounts(b1a2c3d4-e5f6-7890-abcd-1234567890ef)',
    description:
      'Account lookup reference (optional, mutually exclusive with affiliate)',
    type: 'string',
    required: false,
  })
  @IsOptional()
  @IsString({ message: 'Account reference must be a string' })
  'osot_Table_Account@odata.bind'?: string;

  @ApiProperty({
    example:
      'osot_table_account_affiliates(c1a2b3d4-e5f6-7890-abcd-123456789012)',
    description:
      'Affiliate lookup reference (optional, mutually exclusive with account)',
    type: 'string',
    required: false,
  })
  @IsOptional()
  @IsString({ message: 'Affiliate reference must be a string' })
  'osot_Table_Account_Affiliate@odata.bind'?: string;

  // ========================================
  // EMPLOYMENT STATUS
  // ========================================

  @ApiProperty({
    example: EmploymentStatus.EMPLOYEE_SALARIED,
    description: 'Employment status type (single select)',
    enum: EmploymentStatus,
  })
  @IsNotEmpty({ message: 'Employment status is required' })
  @IsEnum(EmploymentStatus, {
    message: 'Employment status must be a valid EmploymentStatus enum value',
  })
  osot_employment_status: EmploymentStatus;

  // ========================================
  // WORK HOURS (MULTIPLE CHOICE)
  // ========================================

  @ApiProperty({
    example: [WorkHours.EXACTLY_35, WorkHours.MORE_THAN_37],
    description: 'Work hours per week (multi-select)',
    enum: WorkHours,
    isArray: true,
  })
  @IsNotEmpty({ message: 'Work hours are required' })
  @IsArray({ message: 'Work hours must be an array' })
  @IsEnum(WorkHours, {
    each: true,
    message: 'Each work hour must be a valid WorkHours enum value',
  })
  osot_work_hours: WorkHours[];

  // ========================================
  // ROLE DESCRIPTOR
  // ========================================

  @ApiProperty({
    example: RoleDescription.DIRECT_INDIRECT_CARE_PROVIDER,
    description: 'Role descriptor (single select)',
    enum: RoleDescription,
  })
  @IsNotEmpty({ message: 'Role descriptor is required' })
  @IsEnum(RoleDescription, {
    message: 'Role descriptor must be a valid RoleDescription enum value',
  })
  osot_role_descriptor: RoleDescription;

  @ApiProperty({
    example: 'Clinical Supervisor',
    description:
      'Other role descriptor (optional, required when role_descriptor = OTHER, max 255 chars)',
    type: 'string',
    required: false,
    maxLength: 255,
  })
  @IsOptional()
  @IsString({ message: 'Role descriptor other must be a string' })
  @MaxLength(255, {
    message: 'Role descriptor other must not exceed 255 characters',
  })
  osot_role_descriptor_other?: string;

  // ========================================
  // PRACTICE YEARS
  // ========================================

  @ApiProperty({
    example: PracticeYears.BETWEEN_6_AND_10_YEARS,
    description: 'Years of practice experience (single select)',
    enum: PracticeYears,
  })
  @IsNotEmpty({ message: 'Practice years are required' })
  @IsEnum(PracticeYears, {
    message: 'Practice years must be a valid PracticeYears enum value',
  })
  osot_practice_years: PracticeYears;

  // ========================================
  // POSITION FUNDING (MULTIPLE CHOICE)
  // ========================================

  @ApiProperty({
    example: [Funding.PROVINCIAL_GOVERMENT_HEALTH, Funding.FEDERAL_GOVERNMENT],
    description: 'Position funding sources (multi-select)',
    enum: Funding,
    isArray: true,
  })
  @IsNotEmpty({ message: 'Position funding is required' })
  @IsArray({ message: 'Position funding must be an array' })
  @IsEnum(Funding, {
    each: true,
    message: 'Each funding source must be a valid Funding enum value',
  })
  osot_position_funding: Funding[];

  @ApiProperty({
    example: 'Private Foundation Grant',
    description:
      'Other position funding (optional, required when position_funding contains OTHER, max 255 chars)',
    type: 'string',
    required: false,
    maxLength: 255,
  })
  @IsOptional()
  @IsString({ message: 'Position funding other must be a string' })
  @MaxLength(255, {
    message: 'Position funding other must not exceed 255 characters',
  })
  osot_position_funding_other?: string;

  // ========================================
  // EMPLOYMENT BENEFITS (MULTIPLE CHOICE)
  // ========================================

  @ApiProperty({
    example: [
      Benefits.EXTENDED_HEALTH_DENTAL_CARE,
      Benefits.PAID_VACATION,
      Benefits.PENSION,
    ],
    description: 'Employment benefits (multi-select)',
    enum: Benefits,
    isArray: true,
  })
  @IsNotEmpty({ message: 'Employment benefits are required' })
  @IsArray({ message: 'Employment benefits must be an array' })
  @IsEnum(Benefits, {
    each: true,
    message: 'Each benefit must be a valid Benefits enum value',
  })
  osot_employment_benefits: Benefits[];

  @ApiProperty({
    example: 'Gym Membership',
    description:
      'Other employment benefits (optional, required when employment_benefits contains OTHER, max 255 chars)',
    type: 'string',
    required: false,
    maxLength: 255,
  })
  @IsOptional()
  @IsString({ message: 'Employment benefits other must be a string' })
  @MaxLength(255, {
    message: 'Employment benefits other must not exceed 255 characters',
  })
  osot_employment_benefits_other?: string;

  // ========================================
  // EARNINGS (3 FIELDS)
  // ========================================

  @ApiProperty({
    example: HourlyEarnings.BETWEEN_41_TO_50,
    description: 'Hourly earnings from employment (single select)',
    enum: HourlyEarnings,
  })
  @IsNotEmpty({ message: 'Earnings employment is required' })
  @IsEnum(HourlyEarnings, {
    message: 'Earnings employment must be a valid HourlyEarnings enum value',
  })
  osot_earnings_employment: HourlyEarnings;

  @ApiProperty({
    example: HourlyEarnings.BETWEEN_51_TO_60,
    description:
      'Hourly earnings from self-employment (direct client billing) (single select)',
    enum: HourlyEarnings,
  })
  @IsNotEmpty({ message: 'Earnings self direct is required' })
  @IsEnum(HourlyEarnings, {
    message: 'Earnings self direct must be a valid HourlyEarnings enum value',
  })
  osot_earnings_self_direct: HourlyEarnings;

  @ApiProperty({
    example: HourlyEarnings.BETWEEN_31_TO_40,
    description:
      'Hourly earnings from self-employment (indirect/subcontracted) (single select)',
    enum: HourlyEarnings,
  })
  @IsNotEmpty({ message: 'Earnings self indirect is required' })
  @IsEnum(HourlyEarnings, {
    message: 'Earnings self indirect must be a valid HourlyEarnings enum value',
  })
  osot_earnings_self_indirect: HourlyEarnings;

  // ========================================
  // UNION NAME
  // ========================================

  @ApiProperty({
    example: 'Ontario Public Service Employees Union',
    description: 'Union name (max 255 chars)',
    type: 'string',
    maxLength: 255,
  })
  @IsNotEmpty({ message: 'Union name is required' })
  @IsString({ message: 'Union name must be a string' })
  @MaxLength(255, { message: 'Union name must not exceed 255 characters' })
  osot_union_name: string;

  // ========================================
  // ANOTHER EMPLOYMENT
  // ========================================

  @ApiProperty({
    example: false,
    description: 'Has another employment position (boolean)',
    type: 'boolean',
  })
  @IsOptional()
  @IsBoolean({ message: 'Another employment must be a boolean' })
  osot_another_employment?: boolean;

  // ========================================
  // SYSTEM PERMISSION FIELDS
  // ========================================

  @ApiProperty({
    example: Privilege.MAIN,
    description: 'User privilege level (system-managed)',
    enum: Privilege,
    required: false,
  })
  @IsOptional()
  @IsEnum(Privilege, {
    message: 'Privilege must be a valid Privilege enum value',
  })
  osot_privilege?: Privilege;

  @ApiProperty({
    example: AccessModifier.PRIVATE,
    description: 'Access modifier controlling visibility (system-managed)',
    enum: AccessModifier,
    required: false,
  })
  @IsOptional()
  @IsEnum(AccessModifier, {
    message: 'Access modifiers must be a valid AccessModifier enum value',
  })
  osot_access_modifiers?: AccessModifier;

  // ========================================
  // SYSTEM TIMESTAMPS
  // ========================================

  @ApiProperty({
    example: '2024-01-15T10:30:00Z',
    description:
      'Creation timestamp (auto-generated by Dataverse, optional for create)',
    type: 'string',
    format: 'date-time',
    required: false,
    readOnly: true,
  })
  @IsOptional()
  @Type(() => Date)
  @IsDate({ message: 'Created on must be a valid date' })
  createdon?: Date;

  @ApiProperty({
    example: '2024-02-20T14:45:00Z',
    description:
      'Last modification timestamp (auto-updated by Dataverse, optional for create)',
    type: 'string',
    format: 'date-time',
    required: false,
    readOnly: true,
  })
  @IsOptional()
  @Type(() => Date)
  @IsDate({ message: 'Modified on must be a valid date' })
  modifiedon?: Date;
}
