/**
 * Order Product Internal Interface
 *
 * Internal representation of Order Product entity within the application.
 * Used throughout services, business rules, and mappers.
 *
 * Architecture Notes:
 * - camelCase naming (TypeScript convention)
 * - Native TypeScript types (Date, number, string)
 * - orderGuid represents the parent order relationship
 * - productId is a string reference (NOT a lookup GUID)
 * - All calculated fields are immutable snapshots
 */

import { AccessModifier, Privilege } from '../../../../common/enums';

/**
 * Order Product entity - Internal representation
 */
export interface OrderProductInternal {
  // ========================================
  // SYSTEM FIELDS
  // ========================================

  /**
   * Unique identifier (GUID/UUID)
   * Example: 'abc-123-def-456-ghi'
   */
  osot_table_order_productid?: string;

  /**
   * Autonumber ID (human-readable)
   * Example: 'osot_ord_prod-0000001'
   * Read-only, generated by Dataverse
   */
  osot_orderproductid?: string;

  /**
   * Record creation timestamp
   */
  createdon?: Date;

  /**
   * Last modification timestamp
   */
  modifiedon?: Date;

  /**
   * Owner ID (user who owns the record)
   */
  ownerid?: string;

  /**
   * State code (0 = Active, 1 = Inactive)
   */
  statecode?: number;

  /**
   * Status code (detailed status)
   */
  statuscode?: number;

  // ========================================
  // RELATIONSHIP FIELDS
  // ========================================

  /**
   * Parent Order GUID (required)
   * Represents the order this line item belongs to
   * Example: 'order-guid-123'
   */
  orderGuid: string;

  // ========================================
  // PRODUCT SNAPSHOT FIELDS (Immutable)
  // ========================================

  /**
   * Product ID reference (string, NOT lookup GUID)
   * Example: 'osot-prod-0000048'
   * Immutable snapshot - preserves reference even if product is deleted
   */
  osot_product_id: string;

  /**
   * Product name at purchase time
   * Example: '2025 Professional Liability - $ 5,000 millions'
   * Immutable snapshot - frozen at checkout
   */
  osot_product_name: string;

  /**
   * Product category at purchase time (immutable snapshot)
   * Values: '0'=Membership, '1'=Insurance, '2'=Other Products
   * Used by event listeners to filter insurance items (category='1')
   * Frozen at checkout - preserves category even if product changes
   * Stored as string in Dataverse (Single line of text field)
   */
  osot_product_category: string;

  /**
   * Insurance type display value at purchase time (text snapshot)
   * Optional because product may not require insurance type
   */
  osot_insurance_type?: string;

  /**
   * Insurance limit amount at purchase time (CAD)
   * Optional snapshot of product insurance coverage frozen at order creation
   * Range: 0.00 to 922,337,203,685,477.00
   * Example: 50000.00, 100000.00, 250000.00
   * Immutable - preserves coverage amount customer agreed to pay for
   */
  osot_insurance_limit?: number;

  /**
   * Additional info/notes from product at purchase time (text snapshot)
   */
  osot_product_additional_info?: string;

  // ========================================
  // QUANTITY & PRICING
  // ========================================

  /**
   * Quantity purchased
   * Example: 1, 2, 3, etc.
   * Immutable after creation
   */
  osot_quantity: number;

  /**
   * Price applied at checkout (CAD)
   * Example: 79.00
   * Immutable snapshot - frozen even if product price changes later
   */
  osot_selectedprice: number;

  /**
   * Tax rate percentage applied
   * Example: 8, 13, 15 (representing 8%, 13%, 15%)
   * Immutable snapshot - frozen at purchase time
   */
  osot_producttax: number;

  // ========================================
  // CALCULATED AMOUNTS (Immutable)
  // ========================================

  /**
   * Calculated tax amount (CAD)
   * Formula: itemSubtotal * (productTaxRate / 100)
   * Example: $158.00 * (13 / 100) = $20.54
   * Immutable - validated but not recalculated
   */
  osot_taxamount: number;

  /**
   * Item subtotal (CAD) - price before tax
   * Formula: selectedPrice * quantity
   * Example: $79.00 * 2 = $158.00
   * Immutable - validated but not recalculated
   */
  osot_itemsubtotal: number;

  /**
   * Item total (CAD) - final price with tax
   * Formula: itemSubtotal + taxAmount
   * Example: $158.00 + $20.54 = $178.54
   * Immutable - validated but not recalculated
   */
  osot_itemtotal: number;

  // ========================================
  // ACCESS CONTROL
  // ========================================

  /**
   * Privilege level (visibility)
   * Values: Public, Internal, Protected, Private
   * Optional - inherited from parent Order if not set
   */
  osot_privilege?: Privilege;

  /**
   * Access modifier (access rules)
   * Values: Owner, Organization, Department, Team, Custom
   * Optional - inherited from parent Order if not set
   */
  osot_access_modifiers?: AccessModifier;
}
