/**
 * Insurance Provider Internal Interface
 *
 * Internal representation of Insurance Provider entity within the application.
 * Used throughout services, business rules, and mappers.
 *
 * Architecture Notes:
 * - camelCase naming (TypeScript convention)
 * - Native TypeScript types (Date, number, string)
 * - organizationGuid represents relationship to parent organization
 */

import { Privilege } from '../../../../common/enums';

/**
 * Insurance Provider entity - Internal representation
 */
export interface InsuranceProviderInternal {
  // ========================================
  // SYSTEM FIELDS
  // ========================================

  /**
   * Unique identifier (GUID/UUID)
   */
  osot_table_insurance_providerid?: string;

  /**
   * Autonumber ID (human-readable)
   * Example: 'osot-prov-0000001'
   * Read-only, generated by Dataverse
   */
  osot_provider_id?: string;

  /**
   * Record creation timestamp
   */
  createdon?: Date;

  /**
   * Last modification timestamp
   */
  modifiedon?: Date;

  /**
   * Owner ID (user who owns the record)
   */
  ownerid?: string;

  /**
   * State code (0 = Active, 1 = Inactive)
   */
  statecode?: number;

  /**
   * Status code (detailed status)
   */
  statuscode?: number;

  // ========================================
  // REQUIRED RELATIONSHIP FIELDS (Immutable)
  // ========================================

  /**
   * Organization GUID (required)
   * Multi-tenant isolation - data belongs to one organization only
   * Immutable after creation
   */
  organizationGuid: string;

  // ========================================
  // PROVIDER INFORMATION (9 fields)
  // ========================================

  /**
   * Insurance company name
   * Required
   */
  osot_insurance_company_name: string;

  /**
   * Insurance broker name
   * Required
   */
  osot_insurance_broker_name: string;

  /**
   * Insurance company logo URL
   * Required
   */
  osot_insurance_company_logo: string;

  /**
   * Insurance broker logo URL
   * Optional
   */
  osot_insurance_broker_logo?: string;

  /**
   * Policy period start date (Date only)
   * Required
   */
  osot_policy_period_start: Date;

  /**
   * Policy period end date (Date only)
   * Required
   */
  osot_policy_period_end: Date;

  /**
   * Master policy description (Text area)
   * Required
   */
  osot_master_policy_description: string;

  /**
   * Insurance authorized representative (URL)
   * Required
   */
  osot_insurance_authorized_representative: string;

  /**
   * Certificate observations (Text area)
   * Optional
   */
  osot_certificate_observations?: string;

  /**
   * Broker general information (Text area)
   * Optional
   */
  osot_broker_general_information?: string;

  // ========================================
  // ACCESS CONTROL (2 optional fields)
  // ========================================

  /**
   * Privilege level (Choice field)
   * Optional - defaults to Main
   */
  osot_privilege?: Privilege;

  /**
   * Access modifier (Choice field)
   * Optional - defaults to Protected
   */
  osot_access_modifier?: number;
}
