/**
 * Contact Basic DTO
 * Integrated with essential modules: errors, utils, enums, constants, validators
 *
 * ESSENTIAL MODULES INTEGRATION:
 * - enums: Uses centralized enums (AccessModifier, Privilege)
 * - constants: References CONTACT_LIMITS for validation consistency
 * - validators: Uses contact validators for comprehensive business rule compliance
 * - utils: Phone formatting and URL sanitization
 *
 * DATAVERSE INTEGRATION:
 * - Field names align with Table Contact.csv schema (osot_ prefix)
 * - Validation rules match Dataverse field constraints
 * - Enum values synchronized with Dataverse global choices
 * - Business required fields properly marked per CSV specification
 * - Social media and contact preferences properly validated
 *
 * This DTO represents the comprehensive contact information structure
 * aligned with Table Contact.csv business requirements and
 * designed for seamless Dataverse integration via DataverseService.
 *
 * Coverage: Essential contact fields, social media information, contact preferences,
 * and access control settings.
 */

import { ApiProperty } from '@nestjs/swagger';
import {
  IsString,
  IsOptional,
  IsEmail,
  IsDateString,
  IsUUID,
  MaxLength,
  Validate,
  Allow,
} from 'class-validator';
import { Transform } from 'class-transformer';

// Essential modules integration
import { CONTACT_LIMITS } from '../constants/contact.constants';
import { formatPhoneNumber } from '../../../../utils/phone-formatter.utils';

// Contact validators integration
import {
  ContactSecondaryEmailValidator,
  ContactJobTitleValidator,
  ContactBusinessWebsiteValidator,
  ContactFacebookUrlValidator,
  ContactInstagramUrlValidator,
  ContactTiktokUrlValidator,
  ContactLinkedinUrlValidator,
} from '../validators/contact.validators';

export class ContactBasicDto {
  // ========================================
  // SYSTEM GENERATED FIELDS
  // ========================================

  @ApiProperty({
    example: 'osot-ct-0000001',
    description: 'Auto-generated contact identifier with string prefix',
    required: false,
    readOnly: true,
  })
  @IsOptional()
  @IsString()
  readonly osot_Contact_ID?: string;

  @ApiProperty({
    example: 'b3e1c1a2-1234-4f56-8a9b-abcdef123456',
    description: 'Unique identifier for contact entity instances',
    required: false,
    readOnly: true,
  })
  @IsOptional()
  @IsUUID()
  readonly osot_table_contactid?: string;

  @ApiProperty({
    example: '2024-01-15T10:30:00Z',
    description: 'Date and time when the contact record was created',
    required: false,
    readOnly: true,
  })
  @IsOptional()
  @IsDateString()
  readonly createdon?: string;

  @ApiProperty({
    example: '2024-01-20T14:45:00Z',
    description: 'Date and time when the contact record was last modified',
    required: false,
    readOnly: true,
  })
  @IsOptional()
  @IsDateString()
  readonly modifiedon?: string;

  @ApiProperty({
    example: 'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
    description: 'Owner identifier for the contact record',
    required: false,
    readOnly: true,
  })
  @IsOptional()
  @IsUUID()
  readonly ownerid?: string;

  // ========================================
  // RELATIONSHIP FIELDS
  // ========================================

  @ApiProperty({
    description:
      'OData bind for Account. Example: "/osot_table_accounts(<GUID>)"',
    example: '',
    required: false,
  })
  @IsOptional()
  @Allow()
  ['osot_Table_Account@odata.bind']?: string;

  // ========================================
  // BUSINESS REQUIRED FIELDS
  // ========================================
  // Note: osot_user_business_id is auto-generated by Dataverse, not included in DTOs

  // ========================================
  // CONTACT INFORMATION FIELDS
  // ========================================

  @ApiProperty({
    example: 'secondary@example.com',
    description: 'Secondary email address (Business Optional)',
    required: false,
    maxLength: CONTACT_LIMITS.SECONDARY_EMAIL_MAX_LENGTH,
  })
  @IsOptional()
  @IsEmail()
  @MaxLength(CONTACT_LIMITS.SECONDARY_EMAIL_MAX_LENGTH)
  @Validate(ContactSecondaryEmailValidator)
  osot_secondary_email?: string;

  @ApiProperty({
    example: 'Senior Developer',
    description: 'Job title (Business Optional)',
    required: false,
    maxLength: CONTACT_LIMITS.JOB_TITLE_MAX_LENGTH,
  })
  @IsOptional()
  @IsString()
  @MaxLength(CONTACT_LIMITS.JOB_TITLE_MAX_LENGTH)
  @Validate(ContactJobTitleValidator)
  osot_job_title?: string;

  @ApiProperty({
    example: '4165551234',
    description: 'Home phone number - Canadian format (Business Optional)',
    required: false,
    maxLength: 14,
  })
  @Transform(({ value }): string | undefined => {
    if (typeof value === 'string') {
      return formatPhoneNumber(value);
    }
    return undefined;
  })
  @IsOptional()
  @IsString()
  @MaxLength(14)
  osot_home_phone?: string;

  @ApiProperty({
    example: '4165559876',
    description: 'Work phone number - Canadian format (Business Optional)',
    required: false,
    maxLength: 14,
  })
  @Transform(({ value }): string | undefined => {
    if (typeof value === 'string') {
      return formatPhoneNumber(value);
    }
    return undefined;
  })
  @IsOptional()
  @IsString()
  @MaxLength(14)
  osot_work_phone?: string;

  // ========================================
  // SOCIAL MEDIA AND WEB PRESENCE FIELDS
  // ========================================

  @ApiProperty({
    example: 'https://example.com',
    description: 'Business website URL (Business Optional)',
    required: false,
    maxLength: CONTACT_LIMITS.BUSINESS_WEBSITE_MAX_LENGTH,
  })
  @IsOptional()
  @IsString()
  @MaxLength(CONTACT_LIMITS.BUSINESS_WEBSITE_MAX_LENGTH)
  @Validate(ContactBusinessWebsiteValidator)
  osot_business_website?: string;

  @ApiProperty({
    example: 'https://facebook.com/johndoe',
    description: 'Facebook profile URL (Business Optional)',
    required: false,
    maxLength: CONTACT_LIMITS.FACEBOOK_MAX_LENGTH,
  })
  @IsOptional()
  @IsString()
  @MaxLength(CONTACT_LIMITS.FACEBOOK_MAX_LENGTH)
  @Validate(ContactFacebookUrlValidator)
  osot_facebook?: string;

  @ApiProperty({
    example: 'https://instagram.com/johndoe',
    description: 'Instagram profile URL (Business Optional)',
    required: false,
    maxLength: CONTACT_LIMITS.INSTAGRAM_MAX_LENGTH,
  })
  @IsOptional()
  @IsString()
  @MaxLength(CONTACT_LIMITS.INSTAGRAM_MAX_LENGTH)
  @Validate(ContactInstagramUrlValidator)
  osot_instagram?: string;

  @ApiProperty({
    example: 'https://tiktok.com/@johndoe',
    description: 'TikTok profile URL (Business Optional)',
    required: false,
    maxLength: CONTACT_LIMITS.TIKTOK_MAX_LENGTH,
  })
  @IsOptional()
  @IsString()
  @MaxLength(CONTACT_LIMITS.TIKTOK_MAX_LENGTH)
  @Validate(ContactTiktokUrlValidator)
  osot_tiktok?: string;

  @ApiProperty({
    example: 'https://linkedin.com/in/johndoe',
    description: 'LinkedIn profile URL (Business Optional)',
    required: false,
    maxLength: CONTACT_LIMITS.LINKEDIN_MAX_LENGTH,
  })
  @IsOptional()
  @IsString()
  @MaxLength(CONTACT_LIMITS.LINKEDIN_MAX_LENGTH)
  @Validate(ContactLinkedinUrlValidator)
  osot_linkedin?: string;

  // ========================================
  // SYSTEM CONTROLLED FIELDS (NOT IN DTOs)
  // ========================================
  // Note: Access control fields (osot_access_modifiers, osot_privilege)
  // are managed by the system and not included in user-facing DTOs
}
