/**
 * Update Contact DTO
 * Contains only user-editable fields for contact updates
 *
 * ESSENTIAL MODULES INTEGRATION:
 * - Includes only fields that users should be able to modify
 * - Excludes system-controlled fields (account binding, privileges, access)
 * - Maintains business rule enforcement for editable fields
 * - Integrates with DataverseService for OData PATCH operations
 *
 * DATAVERSE INTEGRATION:
 * - Supports partial entity updates via OData PATCH requests
 * - Maintains field-level validation for changed properties
 * - Preserves existing values for unspecified fields
 * - Handles optimistic concurrency control through service layer
 *
 * USAGE CONTEXT:
 * - Contact updates via user-facing endpoints
 * - Profile management and self-service updates
 * - API integration for user profile synchronization
 *
 * BUSINESS RULES:
 * - All fields are optional, allowing granular updates
 * - Business rule validation applies to changed combinations
 * - System-controlled fields (account, privileges) are excluded
 * - Social media URL validation maintained
 * - Phone number formatting preserved
 *
 * EXCLUDED FIELDS (System Controlled):
 * - osot_user_business_id: Auto-generated by Dataverse
 * - osot_Table_Account@odata.bind: Account relationship is immutable
 * - osot_access_modifiers: Security setting controlled by system
 * - osot_privilege: User privilege controlled by system
 * - System timestamps and IDs: Managed by Dataverse
 */

import { ApiProperty } from '@nestjs/swagger';
import {
  IsOptional,
  IsEmail,
  IsString,
  MaxLength,
  Validate,
} from 'class-validator';
import { Transform } from 'class-transformer';

// Essential modules integration
import { CONTACT_LIMITS } from '../constants/contact.constants';
import { formatPhoneNumber } from '../../../../utils/phone-formatter.utils';

// Contact validators integration
import {
  ContactSecondaryEmailValidator,
  ContactJobTitleValidator,
  ContactBusinessWebsiteValidator,
  ContactFacebookUrlValidator,
  ContactInstagramUrlValidator,
  ContactTiktokUrlValidator,
  ContactLinkedinUrlValidator,
} from '../validators/contact.validators';

export class UpdateContactDto {
  // ========================================
  // EDITABLE CONTACT INFORMATION FIELDS
  // ========================================

  @ApiProperty({
    example: 'secondary@example.com',
    description: 'Secondary email address (Business Optional)',
    required: false,
    maxLength: CONTACT_LIMITS.SECONDARY_EMAIL_MAX_LENGTH,
  })
  @IsOptional()
  @IsEmail()
  @MaxLength(CONTACT_LIMITS.SECONDARY_EMAIL_MAX_LENGTH)
  @Validate(ContactSecondaryEmailValidator)
  osot_secondary_email?: string;

  @ApiProperty({
    example: 'Senior Developer',
    description: 'Job title (Business Optional)',
    required: false,
    maxLength: CONTACT_LIMITS.JOB_TITLE_MAX_LENGTH,
  })
  @IsOptional()
  @IsString()
  @MaxLength(CONTACT_LIMITS.JOB_TITLE_MAX_LENGTH)
  @Validate(ContactJobTitleValidator)
  osot_job_title?: string;

  @ApiProperty({
    example: '4165551234',
    description: 'Home phone number - Canadian format (Business Optional)',
    required: false,
    maxLength: 14,
  })
  @Transform(({ value }): string | undefined => {
    if (typeof value === 'string') {
      return formatPhoneNumber(value);
    }
    return undefined;
  })
  @IsOptional()
  @IsString()
  @MaxLength(14)
  osot_home_phone?: string;

  @ApiProperty({
    example: '4165559876',
    description: 'Work phone number - Canadian format (Business Optional)',
    required: false,
    maxLength: 14,
  })
  @Transform(({ value }): string | undefined => {
    if (typeof value === 'string') {
      return formatPhoneNumber(value);
    }
    return undefined;
  })
  @IsOptional()
  @IsString()
  @MaxLength(14)
  osot_work_phone?: string;

  @ApiProperty({
    example: 'https://example.com',
    description: 'Business website URL (Business Optional)',
    required: false,
    maxLength: CONTACT_LIMITS.BUSINESS_WEBSITE_MAX_LENGTH,
  })
  @IsOptional()
  @IsString()
  @MaxLength(CONTACT_LIMITS.BUSINESS_WEBSITE_MAX_LENGTH)
  @Validate(ContactBusinessWebsiteValidator)
  osot_business_website?: string;

  // ========================================
  // SOCIAL MEDIA FIELDS (EDITABLE)
  // ========================================

  @ApiProperty({
    example: 'https://facebook.com/johndoe',
    description: 'Facebook profile URL (Business Optional)',
    required: false,
    maxLength: CONTACT_LIMITS.FACEBOOK_MAX_LENGTH,
  })
  @IsOptional()
  @IsString()
  @MaxLength(CONTACT_LIMITS.FACEBOOK_MAX_LENGTH)
  @Validate(ContactFacebookUrlValidator)
  osot_facebook?: string;

  @ApiProperty({
    example: 'https://instagram.com/johndoe',
    description: 'Instagram profile URL (Business Optional)',
    required: false,
    maxLength: CONTACT_LIMITS.INSTAGRAM_MAX_LENGTH,
  })
  @IsOptional()
  @IsString()
  @MaxLength(CONTACT_LIMITS.INSTAGRAM_MAX_LENGTH)
  @Validate(ContactInstagramUrlValidator)
  osot_instagram?: string;

  @ApiProperty({
    example: 'https://tiktok.com/@johndoe',
    description: 'TikTok profile URL (Business Optional)',
    required: false,
    maxLength: CONTACT_LIMITS.TIKTOK_MAX_LENGTH,
  })
  @IsOptional()
  @IsString()
  @MaxLength(CONTACT_LIMITS.TIKTOK_MAX_LENGTH)
  @Validate(ContactTiktokUrlValidator)
  osot_tiktok?: string;

  @ApiProperty({
    example: 'https://linkedin.com/in/johndoe',
    description: 'LinkedIn profile URL (Business Optional)',
    required: false,
    maxLength: CONTACT_LIMITS.LINKEDIN_MAX_LENGTH,
  })
  @IsOptional()
  @IsString()
  @MaxLength(CONTACT_LIMITS.LINKEDIN_MAX_LENGTH)
  @Validate(ContactLinkedinUrlValidator)
  osot_linkedin?: string;
}
