/**
 * Insurance Validation Constants
 *
 * Business rules and validation constraints for Insurance entity:
 * - Field length limits
 * - Numeric ranges
 * - Required field rules
 * - Format patterns
 * - Date validations
 *
 * Based on Dataverse schema in Table_Insurance.csv
 */

/**
 * Field length constraints
 */
export const INSURANCE_FIELD_LENGTH = {
  /**
   * Insurance Number (Autonumber)
   * Format: osot-ins-0000001
   * Generated by Dataverse, not user-provided
   */
  INSURANCE_NUMBER_PREFIX: 'osot-ins',
  INSURANCE_NUMBER_SEED: 1,
  INSURANCE_NUMBER_DIGITS: 7,

  /**
   * Text field constraints
   */
  ACCOUNT_GROUP_MAX: 100,
  CATEGORY_MAX: 100,
  MEMBERSHIP_MAX: 100,
  CERTIFICATE_MAX: 100,
  FIRST_NAME_MAX: 100,
  LAST_NAME_MAX: 100,
  PERSONAL_CORPORATION_MAX: 255,
  ADDRESS_1_MAX: 255,
  ADDRESS_2_MAX: 255,
  CITY_MAX: 255,
  PROVINCE_MAX: 100,
  POSTAL_CODE_MAX: 7,
  PHONE_NUMBER_MAX: 14,
  EMAIL_MAX: 255,
  INSURANCE_TYPE_MAX: 255,

  /**
   * Text area (4000 char limit)
   */
  QUESTION_EXPLAIN_MAX: 4000,
  ENDORSEMENT_DESCRIPTION_MAX: 4000,

  // Aliases for DTO compatibility (without _MAX suffix)
  ACCOUNT_GROUP: 100,
  CATEGORY: 100,
  MEMBERSHIP: 100,
  CERTIFICATE: 100,
  FIRST_NAME: 100,
  LAST_NAME: 100,
  PERSONAL_CORPORATION: 255,
  ADDRESS_1: 255,
  ADDRESS_2: 255,
  CITY: 255,
  PROVINCE: 100,
  POSTAL_CODE: 7,
  PHONE_NUMBER: 14,
  EMAIL: 255,
  INSURANCE_TYPE: 255,
  QUESTION_EXPLANATION: 4000,
  ENDORSEMENT_DESCRIPTION: 4000,
} as const;

/**
 * Numeric field constraints
 */
export const INSURANCE_NUMERIC_CONSTRAINTS = {
  /**
   * Insurance limit constraints (Currency field)
   * Dataverse Currency: 0 to 922,337,203,685,477
   * Business rule: Must be >= 0 (can be 0 for certain plans)
   */
  INSURANCE_LIMIT_MIN: 0,
  INSURANCE_LIMIT_MAX: 922337203685477,

  /**
   * Insurance price constraints (Currency field)
   * Dataverse Currency: 0 to 922,337,203,685,477
   * Business rule: Must be >= 0
   */
  INSURANCE_PRICE_MIN: 0,
  INSURANCE_PRICE_MAX: 922337203685477,

  /**
   * Total constraints (Currency field)
   * Dataverse Currency: 0 to 922,337,203,685,477
   * Formula: total = price + tax
   */
  TOTAL_MIN: 0,
  TOTAL_MAX: 922337203685477,
} as const;

/**
 * Insurance-level validation rules
 */
export const INSURANCE_VALIDATION_RULES = {
  /**
   * Organization is always required (multi-tenant)
   */
  REQUIRES_ORGANIZATION: true,

  /**
   * Order lookup is required (insurance created from order)
   */
  REQUIRES_ORDER: true,

  /**
   * Account (insured person) is required
   */
  REQUIRES_ACCOUNT: true,

  /**
   * All snapshot fields must be present
   */
  REQUIRES_ACCOUNT_GROUP: true,
  REQUIRES_CATEGORY: true,
  REQUIRES_MEMBERSHIP: true,
  REQUIRES_CERTIFICATE: true,
  REQUIRES_FIRST_NAME: true,
  REQUIRES_LAST_NAME: true,
  REQUIRES_ADDRESS_1: true,
  REQUIRES_CITY: true,
  REQUIRES_PROVINCE: true,
  REQUIRES_POSTAL_CODE: true,
  REQUIRES_PHONE_NUMBER: true,
  REQUIRES_EMAIL: true,

  /**
   * Insurance details required
   */
  REQUIRES_INSURANCE_TYPE: true,
  REQUIRES_INSURANCE_LIMIT: true,
  REQUIRES_INSURANCE_PRICE: true,
  REQUIRES_TOTAL: true,

  /**
   * Dates required
   */
  REQUIRES_EFFECTIVE_DATE: true,
  REQUIRES_EXPIRY_DATE: true,

  /**
   * Declaration required
   */
  REQUIRES_INSURANCE_DECLARATION: true,

  /**
   * Effective date must be <= today (cannot backdate beyond today)
   */
  VALIDATE_EFFECTIVE_DATE_NOT_FUTURE: true,

  /**
   * Expiry date must be > effective date
   */
  VALIDATE_EXPIRY_AFTER_EFFECTIVE: true,

  /**
   * Total must equal price (insurance items don't have separate tax in snapshot)
   * OR total = price + embedded_tax if tax was included in price
   */
  VALIDATE_TOTAL_CALCULATION: true,
} as const;

/**
 * Insurance declaration validation
 */
export const INSURANCE_DECLARATION_RULES = {
  /**
   * Declaration field is required (user must declare truthfulness)
   * Value: true/1 or false/0
   */
  REQUIRED: true,

  /**
   * Insurance cannot be created if declaration is false
   * Business rule: User must agree to declaration
   */
  MUST_BE_TRUE_FOR_CREATION: true,
} as const;

/**
 * Insurance question validation rules
 */
export const INSURANCE_QUESTION_RULES = {
  /**
   * Questions 1-3 are optional (default: No/false)
   */
  OPTIONAL: true,

  /**
   * If answer is Yes (true), explanation is required
   */
  EXPLANATION_REQUIRED_IF_YES: true,

  /**
   * Maximum explanation length
   */
  EXPLANATION_MAX_LENGTH: INSURANCE_FIELD_LENGTH.QUESTION_EXPLAIN_MAX,
} as const;

/**
 * Insurance date validation rules
 */
export const INSURANCE_DATE_VALIDATION_RULES = {
  /**
   * Effective date must be on or before today
   */
  EFFECTIVE_DATE_NOT_FUTURE: true,

  /**
   * Expiry date must be after effective date
   */
  EXPIRY_AFTER_EFFECTIVE: true,

  /**
   * Insurance is considered expired if expiry_date < today
   */
  EXPIRY_COMPARISON_INCLUDES_TODAY: false, // expiry_date < today (not <=)

  /**
   * Typical coverage period is 1 year
   * Can be used for warning if expiry - effective > 1 year
   */
  TYPICAL_COVERAGE_MONTHS: 12,
} as const;

/**
 * Error messages for validation failures
 */
export const INSURANCE_VALIDATION_ERRORS = {
  // Required field errors
  REQUIRES_ORGANIZATION: 'Organization (sponsoring entity) is required',
  REQUIRES_ORDER: 'Order reference is required',
  REQUIRES_ACCOUNT: 'Account (insured person) is required',
  REQUIRES_INSURANCE_TYPE: 'Insurance type is required',
  REQUIRES_INSURANCE_LIMIT: 'Insurance limit is required',
  REQUIRES_INSURANCE_PRICE: 'Insurance price is required',
  REQUIRES_TOTAL: 'Insurance total is required',
  REQUIRES_EFFECTIVE_DATE: 'Effective date is required',
  REQUIRES_EXPIRY_DATE: 'Expiry date is required',
  REQUIRES_INSURANCE_DECLARATION: 'Insurance declaration is required',

  // Snapshot field errors
  REQUIRES_ACCOUNT_GROUP: 'Account group (snapshot) is required',
  REQUIRES_CATEGORY: 'Category (snapshot) is required',
  REQUIRES_MEMBERSHIP: 'Membership (snapshot) is required',
  REQUIRES_CERTIFICATE: 'Certificate ID (snapshot) is required',
  REQUIRES_FIRST_NAME: 'First name (snapshot) is required',
  REQUIRES_LAST_NAME: 'Last name (snapshot) is required',
  REQUIRES_ADDRESS_1: 'Address (snapshot) is required',
  REQUIRES_CITY: 'City (snapshot) is required',
  REQUIRES_PROVINCE: 'Province (snapshot) is required',
  REQUIRES_POSTAL_CODE: 'Postal code (snapshot) is required',
  REQUIRES_PHONE_NUMBER: 'Phone number (snapshot) is required',
  REQUIRES_EMAIL: 'Email (snapshot) is required',

  // Date validation errors
  EFFECTIVE_DATE_NOT_FUTURE: 'Effective date cannot be in the future',
  EXPIRY_BEFORE_EFFECTIVE: 'Expiry date must be after effective date',
  EXPIRY_DATE_INVALID: 'Expiry date is invalid or in the past',

  // Declaration errors
  INSURANCE_DECLARATION_REQUIRED: 'Must declare that information is true',
  INSURANCE_DECLARATION_FALSE:
    'Cannot create insurance without accepting declaration',

  // Question errors
  QUESTION_EXPLANATION_REQUIRED:
    'Explanation required when answering Yes to question',

  // Calculation errors
  INVALID_TOTAL_CALCULATION: 'Insurance total does not match price calculation',

  // Numeric range errors
  INSURANCE_LIMIT_BELOW_MIN: `Insurance limit must be at least ${INSURANCE_NUMERIC_CONSTRAINTS.INSURANCE_LIMIT_MIN}`,
  INSURANCE_LIMIT_ABOVE_MAX: `Insurance limit must not exceed ${INSURANCE_NUMERIC_CONSTRAINTS.INSURANCE_LIMIT_MAX}`,
  INSURANCE_PRICE_BELOW_MIN: `Insurance price must be at least ${INSURANCE_NUMERIC_CONSTRAINTS.INSURANCE_PRICE_MIN}`,
  INSURANCE_PRICE_ABOVE_MAX: `Insurance price must not exceed ${INSURANCE_NUMERIC_CONSTRAINTS.INSURANCE_PRICE_MAX}`,
  TOTAL_BELOW_MIN: `Insurance total must be at least ${INSURANCE_NUMERIC_CONSTRAINTS.TOTAL_MIN}`,
  TOTAL_ABOVE_MAX: `Insurance total must not exceed ${INSURANCE_NUMERIC_CONSTRAINTS.TOTAL_MAX}`,

  // Field-specific aliases for DTO usage
  ACCOUNT_GROUP_REQUIRED: 'Account group is required',
  ACCOUNT_GROUP_TOO_LONG: `Account group must not exceed ${INSURANCE_FIELD_LENGTH.ACCOUNT_GROUP} characters`,
  CATEGORY_REQUIRED: 'Category is required',
  CATEGORY_TOO_LONG: `Category must not exceed ${INSURANCE_FIELD_LENGTH.CATEGORY} characters`,
  MEMBERSHIP_REQUIRED: 'Membership is required',
  MEMBERSHIP_TOO_LONG: `Membership must not exceed ${INSURANCE_FIELD_LENGTH.MEMBERSHIP} characters`,
  CERTIFICATE_REQUIRED: 'Certificate ID is required',
  CERTIFICATE_TOO_LONG: `Certificate ID must not exceed ${INSURANCE_FIELD_LENGTH.CERTIFICATE} characters`,
  FIRST_NAME_REQUIRED: 'First name is required',
  FIRST_NAME_TOO_LONG: `First name must not exceed ${INSURANCE_FIELD_LENGTH.FIRST_NAME} characters`,
  LAST_NAME_REQUIRED: 'Last name is required',
  LAST_NAME_TOO_LONG: `Last name must not exceed ${INSURANCE_FIELD_LENGTH.LAST_NAME} characters`,
  PERSONAL_CORPORATION_TOO_LONG: `Personal corporation must not exceed ${INSURANCE_FIELD_LENGTH.PERSONAL_CORPORATION} characters`,
  ADDRESS_1_REQUIRED: 'Address is required',
  ADDRESS_1_TOO_LONG: `Address must not exceed ${INSURANCE_FIELD_LENGTH.ADDRESS_1} characters`,
  ADDRESS_2_TOO_LONG: `Address line 2 must not exceed ${INSURANCE_FIELD_LENGTH.ADDRESS_2} characters`,
  CITY_REQUIRED: 'City is required',
  CITY_TOO_LONG: `City must not exceed ${INSURANCE_FIELD_LENGTH.CITY} characters`,
  PROVINCE_REQUIRED: 'Province is required',
  PROVINCE_TOO_LONG: `Province must not exceed ${INSURANCE_FIELD_LENGTH.PROVINCE} characters`,
  POSTAL_CODE_REQUIRED: 'Postal code is required',
  POSTAL_CODE_TOO_LONG: `Postal code must not exceed ${INSURANCE_FIELD_LENGTH.POSTAL_CODE} characters`,
  PHONE_NUMBER_REQUIRED: 'Phone number is required',
  PHONE_NUMBER_TOO_LONG: `Phone number must not exceed ${INSURANCE_FIELD_LENGTH.PHONE_NUMBER} characters`,
  EMAIL_REQUIRED: 'Email is required',
  EMAIL_TOO_LONG: `Email must not exceed ${INSURANCE_FIELD_LENGTH.EMAIL} characters`,
  INSURANCE_TYPE_REQUIRED: 'Insurance type is required',
  INSURANCE_TYPE_TOO_LONG: `Insurance type must not exceed ${INSURANCE_FIELD_LENGTH.INSURANCE_TYPE} characters`,
  INSURANCE_LIMIT_REQUIRED: 'Insurance limit is required',
  INSURANCE_LIMIT_MIN: `Insurance limit must be at least ${INSURANCE_NUMERIC_CONSTRAINTS.INSURANCE_LIMIT_MIN}`,
  INSURANCE_LIMIT_MAX: `Insurance limit must not exceed ${INSURANCE_NUMERIC_CONSTRAINTS.INSURANCE_LIMIT_MAX}`,
  INSURANCE_PRICE_REQUIRED: 'Insurance price is required',
  INSURANCE_PRICE_MIN: `Insurance price must be at least ${INSURANCE_NUMERIC_CONSTRAINTS.INSURANCE_PRICE_MIN}`,
  INSURANCE_PRICE_MAX: `Insurance price must not exceed ${INSURANCE_NUMERIC_CONSTRAINTS.INSURANCE_PRICE_MAX}`,
  TOTAL_REQUIRED: 'Total is required',
  TOTAL_MIN: `Total must be at least ${INSURANCE_NUMERIC_CONSTRAINTS.TOTAL_MIN}`,
  TOTAL_MAX: `Total must not exceed ${INSURANCE_NUMERIC_CONSTRAINTS.TOTAL_MAX}`,
  INSURANCE_STATUS_REQUIRED: 'Insurance status is required',
  INVALID_INSURANCE_STATUS: 'Invalid insurance status value',
  EFFECTIVE_DATE_REQUIRED: 'Effective date is required',
  EXPIRY_DATE_REQUIRED: 'Expiry date is required',
  QUESTION_EXPLANATION_TOO_LONG: `Question explanation must not exceed ${INSURANCE_FIELD_LENGTH.QUESTION_EXPLANATION} characters`,
  ENDORSEMENT_DESCRIPTION_TOO_LONG: `Endorsement description must not exceed ${INSURANCE_FIELD_LENGTH.ENDORSEMENT_DESCRIPTION} characters`,
  ORGANIZATION_REQUIRED: 'Organization is required',
  INVALID_ORGANIZATION_GUID: 'Invalid organization GUID format',
  ORDER_REQUIRED: 'Order is required',
  INVALID_ORDER_GUID: 'Invalid order GUID format',
  ACCOUNT_REQUIRED: 'Account/User is required',
  INVALID_ACCOUNT_GUID: 'Invalid account GUID format',
} as const;

/**
 * Immutable fields (cannot be updated after creation)
 */
export const INSURANCE_IMMUTABLE_FIELDS = [
  'osot_table_organization', // Organization cannot change
  'osot_table_order', // Order reference cannot change
  'osot_table_account', // Insured person cannot change
  'osot_account_group', // Snapshot frozen
  'osot_category', // Snapshot frozen
  'osot_membership', // Snapshot frozen
  'osot_certificate', // Snapshot frozen
  'osot_first_name', // Snapshot frozen
  'osot_last_name', // Snapshot frozen
  'osot_personal_corporation', // Snapshot frozen
  'osot_address_1', // Snapshot frozen
  'osot_address_2', // Snapshot frozen
  'osot_city', // Snapshot frozen
  'osot_province', // Snapshot frozen
  'osot_postal_code', // Snapshot frozen
  'osot_phone_number', // Snapshot frozen
  'osot_email', // Snapshot frozen
  'osot_insurance_type', // Snapshot frozen
  'osot_insurance_limit', // Snapshot frozen
  'osot_insurance_price', // Snapshot frozen
  'osot_total', // Snapshot frozen
  'osot_effective_date', // Coverage start date frozen
  'osot_insurance_declaration', // Declaration frozen
] as const;

/**
 * Partially immutable fields (can only transition through valid states)
 */
export const INSURANCE_STATE_TRANSITION_RULES = {
  /**
   * Insurance status has valid transitions
   * DRAFT → PENDING → ACTIVE → (EXPIRED | CANCELLED | SUSPENDED)
   */
  STATUS_HAS_VALID_TRANSITIONS: true,

  /**
   * Can add endorsement to active certificate
   */
  CAN_ADD_ENDORSEMENT_WHEN_ACTIVE: true,

  /**
   * Cannot change endorsement details once applied
   */
  ENDORSEMENT_IMMUTABLE_AFTER_EFFECTIVE: true,
} as const;
